export type DesignSystemComponentStatus = 'admitted' | 'candidate' | 'deferred' | 'excluded';
export type DesignSystemComponentTier = 'feature-component' | 'ui';

export interface DesignSystemComponentManifestEntry {
  id: string;
  componentName: string;
  sourcePath: string;
  ownerFeature: string;
  status: DesignSystemComponentStatus;
  tier: DesignSystemComponentTier;
  decisionReason: string;
  matchedPatterns: readonly string[];
  suggestedDesignComponent?: string;
  storyPath?: string;
  storybookTitle?: string;
  catalogGroupId?: string;
  requiredStates?: readonly string[];
  mockDataSources?: readonly string[];
  revisitTrigger?: string;
}

const debugPanelStoryPath = 'frontend/src/features/debug/components/DebugPanelComponents.stories.tsx';
const debugPanelStorybookTitle = 'Design System/Feature Components/Debug Panel';
const codexBinaryStoryPath = 'frontend/src/features/codex-binary/components/CodexBinaryComponents.stories.tsx';
const codexBinaryStorybookTitle = 'Design System/Feature Components/Codex Binary';
const accountModalStoryPath = 'frontend/src/features/accounts/components/AccountModalComponents.stories.tsx';
const accountModalStorybookTitle = 'Design System/Feature Components/Account Modals';
const accountCardStoryPath = 'frontend/src/features/accounts/components/AccountCardComponents.stories.tsx';
const accountCardStorybookTitle = 'Design System/Feature Components/Account Cards';
const statusRelayEditorsStoryPath = 'frontend/src/features/status/components/StatusRelayEditors.stories.tsx';
const statusRelayEditorsStorybookTitle = 'Design System/Feature Components/Status Relay Editors';
const statusSnippetPanelStoryPath = 'frontend/src/features/status/components/StatusSnippetPanel.stories.tsx';
const statusSnippetPanelStorybookTitle = 'Design System/Feature Components/Status Snippet Panel';
const usageDeskStoryPath = 'frontend/src/features/accounts/components/usage-desk/UsageDeskComponents.stories.tsx';
const usageDeskStorybookTitle = 'Design System/Feature Components/Usage Desk';

export const designSystemComponentManifest = [
  {
    id: 'accounts-account-card',
    componentName: 'AccountCard',
    sourcePath: 'frontend/src/features/accounts/components/AccountCard.tsx',
    ownerFeature: 'accounts',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '账号卡片可渲染但包含下载 auth file 等 Wails 入口，先收编更纯的 Attribution/CardSections 后再拆交互边界。',
    matchedPatterns: ['DebugPanel EntryCard'],
    suggestedDesignComponent: 'AccountAttributionCard',
    revisitTrigger: 'AccountCard 的 Wails 操作入口可由 props/mock 边界隔离后复查。',
  },
  {
    id: 'accounts-account-card-frame',
    componentName: 'AccountCardFrame',
    sourcePath: 'frontend/src/features/accounts/components/AccountCardFrame.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '可点击卡片外壳已通过 Account Cards story 收编，覆盖默认、选中和嵌套 action 边界。',
    matchedPatterns: ['DesignSystemStoryFrame'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['default', 'interactive-child', 'selected'],
    mockDataSources: ['storybook local mock'],
  },
  {
    id: 'accounts-account-card-skeleton',
    componentName: 'AccountCardSkeleton',
    sourcePath: 'frontend/src/features/accounts/components/AccountCardSkeleton.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号卡骨架屏已通过 Account Cards story 收编，覆盖卡片加载矩阵。',
    matchedPatterns: ['PageLoadingFallback'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['full', 'compact'],
    mockDataSources: ['storybook local mock'],
  },
  {
    id: 'accounts-account-detail-modal-frame',
    componentName: 'AccountDetailModalFrame',
    sourcePath: 'frontend/src/features/accounts/components/AccountDetailModalFrame.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号详情弹窗 shell 已通过 Account Modals story 收编，覆盖 header、滚动内容、错误条和 footer action。',
    matchedPatterns: ['DebugPanel details'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['default', 'long-content'],
    mockDataSources: ['storybook account modal content mock'],
  },
  {
    id: 'accounts-account-group-section',
    componentName: 'AccountGroupSection',
    sourcePath: 'frontend/src/features/accounts/components/AccountGroupSection.tsx',
    ownerFeature: 'accounts',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: '分组标题和卡片网格可 mock，但会组合账号卡，排在卡片基础构件之后。',
    matchedPatterns: ['DebugPanel grouped list'],
    suggestedDesignComponent: 'GroupedCardSection',
    requiredStates: ['grid', 'list', 'empty'],
  },
  {
    id: 'accounts-account-health-bar',
    componentName: 'AccountHealthBar',
    sourcePath: 'frontend/src/features/accounts/components/AccountHealthBar.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号健康条已通过 Account Cards story 收编，覆盖健康、混合失败和空闲块。',
    matchedPatterns: ['DebugPanel status card'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['healthy', 'warning', 'failed'],
    mockDataSources: ['storybook AccountUsageSummary mock'],
  },
  {
    id: 'accounts-account-proxy-route-section',
    componentName: 'AccountProxyRouteSection',
    sourcePath: 'frontend/src/features/accounts/components/AccountProxyRouteSection.tsx',
    ownerFeature: 'accounts',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '会读取 localStorage 中 proxy-pool 数据，需先抽出纯 selector view 或固定 preview 数据。',
    matchedPatterns: ['SegmentedControl', 'Combobox'],
    suggestedDesignComponent: 'ProxyRouteSelector',
    revisitTrigger: 'proxy 节点来源可由 props 注入后复查。',
  },
  {
    id: 'accounts-account-rotation-modal',
    componentName: 'AccountRotationModal',
    sourcePath: 'frontend/src/features/accounts/components/AccountRotationModal.tsx',
    ownerFeature: 'accounts',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '依赖 useAccountRotation 加载/保存真实配置，不直接进入 Storybook；先拆纯 view。',
    matchedPatterns: ['ToggleSwitch', 'SegmentedControl'],
    suggestedDesignComponent: 'RotationSettingsDialog',
    revisitTrigger: '轮换 modal 拆出纯展示层后复查。',
  },
  {
    id: 'accounts-accounts-header',
    componentName: 'AccountsHeader',
    sourcePath: 'frontend/src/features/accounts/components/AccountsHeader.tsx',
    ownerFeature: 'accounts',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: '账号页头可匹配 WorkspacePageHeader，但上传 input 和动作菜单需要 mock。',
    matchedPatterns: ['WorkspacePageHeader'],
    suggestedDesignComponent: 'WorkspaceActionMenu',
    requiredStates: ['default', 'loading', 'with-actions'],
  },
  {
    id: 'accounts-accounts-toolbar',
    componentName: 'AccountsToolbar',
    sourcePath: 'frontend/src/features/accounts/components/AccountsToolbar.tsx',
    ownerFeature: 'accounts',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: '搜索、筛选和密度切换是可复用工作台工具栏模式。',
    matchedPatterns: ['SegmentedControl'],
    suggestedDesignComponent: 'FilterMenuToolbar',
    requiredStates: ['empty-selection', 'bulk-selection', 'filters-open'],
  },
  {
    id: 'accounts-api-key-compose-modal',
    componentName: 'ApiKeyComposeModal',
    sourcePath: 'frontend/src/features/accounts/components/ApiKeyComposeModal.tsx',
    ownerFeature: 'accounts',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: '新增 API key 弹窗动作由 props 注入，可用 mock 探测状态。',
    matchedPatterns: ['Combobox'],
    suggestedDesignComponent: 'CredentialComposeDialog',
    requiredStates: ['empty', 'fetching-models', 'verify-error'],
  },
  {
    id: 'accounts-api-key-detail-modal',
    componentName: 'ApiKeyDetailModal',
    sourcePath: 'frontend/src/features/accounts/components/ApiKeyDetailModal.tsx',
    ownerFeature: 'accounts',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '详情弹窗数据重且包含保存/验证/测试路径，先收编内部小组件和 modal shell。',
    matchedPatterns: ['Combobox', 'ToggleSwitch', 'DebugPanel details'],
    suggestedDesignComponent: 'CredentialDetailDialog',
    revisitTrigger: '详情页区块拆分或 mock handlers 稳定后复查。',
  },
  {
    id: 'accounts-attribution-card',
    componentName: 'AttributionCard',
    sourcePath: 'frontend/src/features/accounts/components/AttributionCard.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '归因卡已通过 Account Cards story 收编，覆盖健康、失败、紧凑和列表密度。',
    matchedPatterns: ['DebugPanel EntryCard'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['healthy', 'limited', 'failed', 'long-content'],
    mockDataSources: ['storybook AccountUsageSummary mock', 'storybook quota/billing/rate-limit mock'],
  },
  {
    id: 'accounts-card-sections',
    componentName: 'CardSections',
    sourcePath: 'frontend/src/features/accounts/components/CardSections.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号指标段已通过 Account Cards story 收编，覆盖 quota、billing、usage、rate-limit 和 evidence。',
    matchedPatterns: ['DebugPanel state matrix'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['quota', 'usage', 'billing', 'rate-limit', 'evidence'],
    mockDataSources: ['storybook quota/billing/usage/rate-limit mock'],
  },
  {
    id: 'accounts-codex-oauth-modal',
    componentName: 'CodexOAuthModal',
    sourcePath: 'frontend/src/features/accounts/components/CodexOAuthModal.tsx',
    ownerFeature: 'accounts',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: 'OAuth URL 展示可用 mock handler，适合归入链接/复制弹窗模式。',
    matchedPatterns: ['DebugPanel empty/state'],
    suggestedDesignComponent: 'OAuthLinkDialog',
    requiredStates: ['ready', 'copied', 'disabled'],
  },
  {
    id: 'accounts-openai-compatible-compose-modal',
    componentName: 'OpenAICompatibleComposeModal',
    sourcePath: 'frontend/src/features/accounts/components/OpenAICompatibleComposeModal.tsx',
    ownerFeature: 'accounts',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: 'provider 新增表单为纯 props，可进入表单 modal 模式。',
    matchedPatterns: ['ActionSelect'],
    suggestedDesignComponent: 'ProviderComposeDialog',
    requiredStates: ['empty', 'preset-selected', 'validation-error'],
  },
  {
    id: 'accounts-openai-compatible-detail-modal',
    componentName: 'OpenAICompatibleDetailModal',
    sourcePath: 'frontend/src/features/accounts/components/OpenAICompatibleDetailModal.tsx',
    ownerFeature: 'accounts',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '嵌入 RateLimitRulesSection，需先隔离 Wails fallback 或拆区块。',
    matchedPatterns: ['Combobox', 'ToggleSwitch'],
    suggestedDesignComponent: 'ProviderDetailDialog',
    revisitTrigger: '限流规则编辑器可 mock 后复查。',
  },
  {
    id: 'accounts-openai-compatible-provider-card',
    componentName: 'OpenAICompatibleProviderCard',
    sourcePath: 'frontend/src/features/accounts/components/OpenAICompatibleProviderCard.tsx',
    ownerFeature: 'accounts',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: 'provider 卡片为纯 props，能验证账号卡体系是否统一。',
    matchedPatterns: ['DebugPanel EntryCard'],
    suggestedDesignComponent: 'ProviderTelemetryCard',
    requiredStates: ['ready', 'error', 'disabled'],
  },
  {
    id: 'accounts-openai-compatible-workspace',
    componentName: 'OpenAICompatibleWorkspace',
    sourcePath: 'frontend/src/features/accounts/components/OpenAICompatibleWorkspace.tsx',
    ownerFeature: 'accounts',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: 'workspace view 可用 mock provider 列表，但属于组合级组件，排在 provider card 之后。',
    matchedPatterns: ['WorkspacePageHeader', 'PageLoadingFallback'],
    suggestedDesignComponent: 'ProviderWorkspaceView',
    requiredStates: ['loading', 'empty', 'grid'],
  },
  {
    id: 'accounts-paste-auth-modal',
    componentName: 'PasteAuthModal',
    sourcePath: 'frontend/src/features/accounts/components/PasteAuthModal.tsx',
    ownerFeature: 'accounts',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: '粘贴导入弹窗为纯 props，适合 modal shell 收编后纳入。',
    matchedPatterns: ['DebugPanel details'],
    suggestedDesignComponent: 'PasteImportDialog',
    requiredStates: ['empty', 'invalid-json', 'ready'],
  },
  {
    id: 'accounts-rate-limit-rules-section',
    componentName: 'RateLimitRulesSection',
    sourcePath: 'frontend/src/features/accounts/components/RateLimitRulesSection.tsx',
    ownerFeature: 'accounts',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '直接 import Wails rate-limit API，需固定 browser fallback 或拆纯规则列表。',
    matchedPatterns: ['ToggleSwitch'],
    suggestedDesignComponent: 'RuleEditorList',
    revisitTrigger: '规则编辑数据层抽离后复查。',
  },
  {
    id: 'accounts-unified-account-detail-modal',
    componentName: 'UnifiedAccountDetailModal',
    sourcePath: 'frontend/src/features/accounts/components/UnifiedAccountDetailModal.tsx',
    ownerFeature: 'accounts',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '直接调用 auth file 下载、模型读取和内容清洗，不直接进入设计系统。',
    matchedPatterns: ['Combobox', 'ToggleSwitch'],
    suggestedDesignComponent: 'AccountDetailWorkbench',
    revisitTrigger: '拆出无 Wails sections 后复查。',
  },
  {
    id: 'accounts-unified-compose-modal',
    componentName: 'UnifiedComposeModal',
    sourcePath: 'frontend/src/features/accounts/components/UnifiedComposeModal.tsx',
    ownerFeature: 'accounts',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: '供应商 preset 两步弹窗为稳定模式，可用 mock presets 收编。',
    matchedPatterns: ['ActionSelect'],
    suggestedDesignComponent: 'ProviderPresetPicker',
    requiredStates: ['preset-list', 'form-step', 'error'],
  },
  {
    id: 'accounts-rotation-config-section',
    componentName: 'RotationConfigSection',
    sourcePath: 'frontend/src/features/accounts/components/account-rotation/RotationConfigSection.tsx',
    ownerFeature: 'accounts',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: 'routing 表单无直接 Wails 调用，可用 mock routingDraft 收编。',
    matchedPatterns: ['Combobox', 'ToggleSwitch'],
    suggestedDesignComponent: 'RoutingConfigForm',
    requiredStates: ['priority', 'random', 'disabled'],
  },
  {
    id: 'accounts-rotation-priority-item',
    componentName: 'RotationPriorityItem',
    sourcePath: 'frontend/src/features/accounts/components/account-rotation/RotationPriorityItem.tsx',
    ownerFeature: 'accounts',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: '可拖拽优先级项为纯 props，适合高密度条目模式。',
    matchedPatterns: ['DebugPanel EntryCard'],
    suggestedDesignComponent: 'DraggablePriorityItem',
    requiredStates: ['normal', 'dragging', 'disabled'],
  },
  {
    id: 'accounts-usage-desk-chart',
    componentName: 'UsageDeskChart',
    sourcePath: 'frontend/src/features/accounts/components/usage-desk/UsageDeskChart.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Usage Desk 图表已通过 Usage Desk story 收编，覆盖双曲线、选中点、控件区和空态。',
    matchedPatterns: ['DebugPanel state matrix'],
    storyPath: usageDeskStoryPath,
    storybookTitle: usageDeskStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['observed', 'projected', 'empty'],
    mockDataSources: ['storybook usage chart point mock'],
  },
  {
    id: 'accounts-usage-desk-panels',
    componentName: 'UsageDeskPanels',
    sourcePath: 'frontend/src/features/accounts/components/usage-desk/UsageDeskPanels.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Usage Desk 信息面板和 session drilldown 已通过 Usage Desk story 收编，覆盖 totals、session rows 和空会话。',
    matchedPatterns: ['DebugPanel Empty', 'DebugPanel EntryCard'],
    storyPath: usageDeskStoryPath,
    storybookTitle: usageDeskStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['totals', 'session-drilldown', 'empty'],
    mockDataSources: ['storybook usage session mock'],
  },
  {
    id: 'accounts-usage-detail-table',
    componentName: 'UsageDetailTable',
    sourcePath: 'frontend/src/features/accounts/components/usage-desk/UsageDetailTable.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Usage 明细表已通过 Usage Desk story 收编，覆盖 projected columns、选中行和空表。',
    matchedPatterns: ['DebugPanel log table'],
    storyPath: usageDeskStoryPath,
    storybookTitle: usageDeskStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['daily', 'selected', 'empty'],
    mockDataSources: ['storybook usage minute row mock'],
  },
  {
    id: 'codex-binary-summary-panel',
    componentName: 'CodexBinarySummaryPanel',
    sourcePath: 'frontend/src/features/codex-binary/components/CodexBinarySummaryPanel.tsx',
    ownerFeature: 'codex-binary',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '运行时版本摘要已通过 Codex Binary story 收编，覆盖托管 PATH、doctor error 和刷新动作。',
    matchedPatterns: ['WorkspacePageHeader'],
    storyPath: codexBinaryStoryPath,
    storybookTitle: codexBinaryStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['managed-path-disabled', 'managed-path-enabled', 'doctor-error'],
    mockDataSources: ['codexBinaryPreviewSnapshot'],
  },
  {
    id: 'codex-binary-version-cell',
    componentName: 'CodexBinaryVersionCell',
    sourcePath: 'frontend/src/features/codex-binary/components/CodexBinaryVersionCell.tsx',
    ownerFeature: 'codex-binary',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '可展开版本行已通过 Codex Binary story 收编，覆盖 active/download/expanded release notes。',
    matchedPatterns: ['ActionSelect', 'DebugPanel details'],
    storyPath: codexBinaryStoryPath,
    storybookTitle: codexBinaryStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['active', 'downloadable', 'expanded-notes'],
    mockDataSources: ['codexBinaryPreviewSnapshot', 'codexBinaryPreviewNotes'],
  },
  {
    id: 'codex-binary-version-list',
    componentName: 'CodexBinaryVersionList',
    sourcePath: 'frontend/src/features/codex-binary/components/CodexBinaryVersionList.tsx',
    ownerFeature: 'codex-binary',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '版本列表已通过 Codex Binary story 收编，覆盖筛选、展开行和空态。',
    matchedPatterns: ['SegmentedControl', 'DebugPanel list'],
    storyPath: codexBinaryStoryPath,
    storybookTitle: codexBinaryStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['stable-filter', 'all-filter', 'empty'],
    mockDataSources: ['codexBinaryPreviewSnapshot'],
  },
  {
    id: 'codex-account-detail-modal',
    componentName: 'CodexAccountDetailModal',
    sourcePath: 'frontend/src/features/codex/components/CodexAccountDetailModal.tsx',
    ownerFeature: 'codex',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: '账号详情保存由 props 注入，可用 mock 模型映射收编。',
    matchedPatterns: ['Combobox'],
    suggestedDesignComponent: 'EntityDetailModal',
    requiredStates: ['mapped', 'empty-models', 'saving'],
  },
  {
    id: 'codex-account-list-view',
    componentName: 'CodexAccountListView',
    sourcePath: 'frontend/src/features/codex/components/CodexAccountListView.tsx',
    ownerFeature: 'codex',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '组合整个 account-list workspace，先收编下层 row/section/probe 组件。',
    matchedPatterns: ['WorkspacePageHeader', 'PageLoadingFallback'],
    suggestedDesignComponent: 'AccountListWorkspaceView',
    revisitTrigger: 'CodexAccountOrderRow/Section 和 ProbeCard 已有 stories 后复查。',
  },
  {
    id: 'codex-account-order-row',
    componentName: 'CodexAccountOrderRow',
    sourcePath: 'frontend/src/features/codex/components/CodexAccountOrderRow.tsx',
    ownerFeature: 'codex',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: '纯 props 排序行，适合高密度条目和密度模式回归。',
    matchedPatterns: ['ToggleSwitch', 'DebugPanel EntryCard'],
    suggestedDesignComponent: 'SortableAccountOrderRow',
    requiredStates: ['full', 'compact', 'list', 'disabled'],
  },
  {
    id: 'codex-account-order-section',
    componentName: 'CodexAccountOrderSection',
    sourcePath: 'frontend/src/features/codex/components/CodexAccountOrderSection.tsx',
    ownerFeature: 'codex',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: '排序列表容器无 Wails，localStorage/hash 可接受 mock 环境。',
    matchedPatterns: ['SegmentedControl', 'DebugPanel list'],
    suggestedDesignComponent: 'WorkspaceListSection',
    requiredStates: ['full', 'compact', 'list', 'empty'],
  },
  {
    id: 'codex-route-probe-card',
    componentName: 'CodexRouteProbeCard',
    sourcePath: 'frontend/src/features/codex/components/CodexRouteProbeCard.tsx',
    ownerFeature: 'codex',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: '路由探测工作台为纯 props，可用 mock 日志和候选队列收编。',
    matchedPatterns: ['ToggleSwitch', 'Combobox', 'DebugPanel'],
    suggestedDesignComponent: 'RouteProbeWorkbenchModal',
    requiredStates: ['idle', 'running', 'failed'],
  },
  {
    id: 'codex-model-combobox',
    componentName: 'ModelCombobox',
    sourcePath: 'frontend/src/features/codex/components/ModelCombobox.tsx',
    ownerFeature: 'codex',
    status: 'excluded',
    tier: 'feature-component',
    decisionReason: '只是 Combobox 的 Codex 模型薄包装，设计系统价值并入基础 Combobox，不单独收编。',
    matchedPatterns: ['Combobox'],
    suggestedDesignComponent: 'Combobox',
  },
  {
    id: 'debug-empty-state',
    componentName: 'DebugEmptyState',
    sourcePath: 'frontend/src/features/debug/components/DebugEmptyState.tsx',
    ownerFeature: 'debug',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '调试面板空状态已通过 Debug Panel story 收编。',
    matchedPatterns: ['DebugPanel Empty'],
    storyPath: debugPanelStoryPath,
    storybookTitle: debugPanelStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['empty'],
    mockDataSources: ['storybook local mock'],
  },
  {
    id: 'debug-entry-card',
    componentName: 'DebugEntryCard',
    sourcePath: 'frontend/src/features/debug/components/DebugEntryCard.tsx',
    ownerFeature: 'debug',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '调试日志卡片已通过 Debug Panel story 收编，覆盖成功、错误、折叠和选中状态。',
    matchedPatterns: ['DebugPanel EntryCard'],
    storyPath: debugPanelStoryPath,
    storybookTitle: debugPanelStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['success', 'error', 'collapsed', 'selected'],
    mockDataSources: ['storybook request/response mock'],
  },
  {
    id: 'debug-header',
    componentName: 'DebugHeader',
    sourcePath: 'frontend/src/features/debug/components/DebugHeader.tsx',
    ownerFeature: 'debug',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '调试面板工具栏已通过 Debug Panel story 收编。',
    matchedPatterns: ['DebugPanel toolbar'],
    storyPath: debugPanelStoryPath,
    storybookTitle: debugPanelStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['default', 'all-selected', 'copy-success'],
    mockDataSources: ['storybook local mock'],
  },
  {
    id: 'status-relay-editors',
    componentName: 'RelayEditors',
    sourcePath: 'frontend/src/features/status/components/RelayEditors.tsx',
    ownerFeature: 'status',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Relay key/provider/model editor modals 已通过 Status Relay Editors story 收编，覆盖创建、重命名、错误和模型输入状态。',
    matchedPatterns: ['DesignSystemStoryFrame'],
    storyPath: statusRelayEditorsStoryPath,
    storybookTitle: statusRelayEditorsStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['key-editor', 'provider-editor', 'model-editor'],
    mockDataSources: ['storybook relay editor state mock'],
  },
  {
    id: 'status-panels',
    componentName: 'StatusPanels',
    sourcePath: 'frontend/src/features/status/components/StatusPanels.tsx',
    ownerFeature: 'status',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: '包含多个纯 props 面板但状态复杂；StatusSnippetPanel 已拆出收编，剩余 Codex feature list 和 local apply 面板继续分批处理。',
    matchedPatterns: ['SegmentedControl', 'ActionSelect', 'ToggleSwitch', 'DebugPanel details'],
    suggestedDesignComponent: 'LocalCliApplyPanel',
    requiredStates: ['ready', 'blocked', 'saving', 'diff'],
  },
  {
    id: 'status-snippet-panel',
    componentName: 'StatusSnippetPanel',
    sourcePath: 'frontend/src/features/status/components/StatusSnippetPanel.tsx',
    ownerFeature: 'status',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Status 配置片段面板已拆成独立组件并通过 Status Snippet Panel story 收编，覆盖普通配置、diff、长行和 header action。',
    matchedPatterns: ['DebugPanel details'],
    storyPath: statusSnippetPanelStoryPath,
    storybookTitle: statusSnippetPanelStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['plain', 'diff', 'long-line', 'header-action'],
    mockDataSources: ['storybook local config snippet mock'],
  },
] as const satisfies readonly DesignSystemComponentManifestEntry[];

export function getAdmittedDesignSystemComponentManifest() {
  return designSystemComponentManifest.filter((entry) => entry.status === 'admitted');
}
