export type DesignSystemComponentStatus = 'admitted' | 'candidate' | 'deferred' | 'excluded';
export type DesignSystemComponentTier = 'feature-component' | 'ui';

export interface DesignSystemComponentManifestEntry {
  id: string;
  componentName: string;
  sourcePath: string;
  ownerFeature: string;
  status: DesignSystemComponentStatus;
  tier: DesignSystemComponentTier;
  decisionReason: string;
  matchedPatterns: readonly string[];
  suggestedDesignComponent?: string;
  storyPath?: string;
  storybookTitle?: string;
  previewPath?: string;
  previewTitle?: string;
  catalogGroupId?: string;
  requiredStates?: readonly string[];
  mockDataSources?: readonly string[];
  revisitTrigger?: string;
}

const debugPanelStoryPath = 'frontend/src/features/debug/components/DebugPanelComponents.stories.tsx';
const debugPanelStorybookTitle = 'Design System/业务组件/调试面板';
const codexBinaryStoryPath = 'frontend/src/features/codex-binary/components/CodexBinaryComponents.stories.tsx';
const codexBinaryStorybookTitle = 'Design System/业务组件/Codex 二进制';
const accountModalStoryPath = 'frontend/src/features/accounts/components/AccountModalComponents.stories.tsx';
const accountModalStorybookTitle = 'Design System/业务组件/账号弹窗';
const accountsHeaderStoryPath = 'frontend/src/features/accounts/components/AccountsHeaderComponents.stories.tsx';
const accountsHeaderStorybookTitle = 'Design System/业务组件/账号页头';
const accountsToolbarStoryPath = 'frontend/src/features/accounts/components/AccountsToolbarComponents.stories.tsx';
const accountsToolbarStorybookTitle = 'Design System/业务组件/账号工具栏';
const accountsListStoryPath = 'frontend/src/features/accounts/components/AccountsListComponents.stories.tsx';
const accountsListStorybookTitle = 'Design System/业务组件/账号列表';
const accountGroupSectionStoryPath = 'frontend/src/features/accounts/components/AccountGroupSectionComponents.stories.tsx';
const accountGroupSectionStorybookTitle = 'Design System/业务组件/账号分组';
const accountProxyRouteStoryPath = 'frontend/src/features/accounts/components/AccountProxyRouteSection.stories.tsx';
const accountProxyRouteStorybookTitle = 'Design System/业务组件/账号代理出口';
const rateLimitRulesStoryPath = 'frontend/src/features/accounts/components/RateLimitRulesSection.stories.tsx';
const rateLimitRulesStorybookTitle = 'Design System/业务组件/限流规则';
const accountCardStoryPath = 'frontend/src/features/accounts/components/AccountCardComponents.stories.tsx';
const accountCardStorybookTitle = 'Design System/业务组件/账号卡片';
const openAICompatibleStoryPath = 'frontend/src/features/accounts/components/OpenAICompatibleComponents.stories.tsx';
const openAICompatibleStorybookTitle = 'Design System/业务组件/OpenAI 兼容';
const accountRotationStoryPath = 'frontend/src/features/accounts/components/account-rotation/AccountRotationComponents.stories.tsx';
const accountRotationStorybookTitle = 'Design System/业务组件/账号轮换';
const statusRelayEditorsStoryPath = 'frontend/src/features/status/components/StatusRelayEditors.stories.tsx';
const statusRelayEditorsStorybookTitle = 'Design System/业务组件/状态页 Relay 编辑器';
const statusCodexFeaturesStoryPath = 'frontend/src/features/status/components/StatusCodexFeaturesSection.stories.tsx';
const statusCodexFeaturesStorybookTitle = 'Design System/业务组件/状态页 Codex 功能';
const statusCodexRootSettingsStoryPath = 'frontend/src/features/status/components/StatusCodexRootSettingsSection.stories.tsx';
const statusCodexRootSettingsStorybookTitle = 'Design System/业务组件/状态页 Codex Root Settings';
const statusCodexModelProvidersStoryPath = 'frontend/src/features/status/components/StatusCodexModelProvidersSection.stories.tsx';
const statusCodexModelProvidersStorybookTitle = 'Design System/业务组件/状态页 Codex Model Providers';
const statusCodexNoticeStoryPath = 'frontend/src/features/status/components/StatusCodexNoticeSection.stories.tsx';
const statusCodexNoticeStorybookTitle = 'Design System/业务组件/状态页 Codex Notices';
const statusLocalCliApplyStoryPath = 'frontend/src/features/status/components/StatusLocalCliApplyPanel.stories.tsx';
const statusLocalCliApplyStorybookTitle = 'Design System/业务组件/状态页本地 CLI 应用';
const statusSnippetPanelStoryPath = 'frontend/src/features/status/components/StatusSnippetPanel.stories.tsx';
const statusSnippetPanelStorybookTitle = 'Design System/业务组件/状态页片段面板';
const settingsReleasePanelStoryPath = 'frontend/src/features/settings/components/SettingsReleasePanel.stories.tsx';
const settingsReleasePanelStorybookTitle = 'Design System/业务组件/设置更新面板';
const usageDeskStoryPath = 'frontend/src/features/accounts/components/usage-desk/UsageDeskComponents.stories.tsx';
const usageDeskStorybookTitle = 'Design System/业务组件/用量工作台';
const claudeCodeAccountListStoryPath = 'frontend/src/features/claude-code/components/ClaudeCodeAccountListWorkbench.stories.tsx';
const claudeCodeAccountListStorybookTitle = 'Design System/业务组件/Claude Code 账号列表';
const claudeCodeAssetWorkbenchStoryPath = 'frontend/src/features/claude-code/components/ClaudeCodeAssetWorkbench.stories.tsx';
const claudeCodeAssetWorkbenchStorybookTitle = 'Design System/业务组件/Claude Code 资产工作台';
const claudeCodeSubagentCatalogStoryPath = 'frontend/src/features/claude-code/components/ClaudeCodeSubagentCatalog.stories.tsx';
const claudeCodeMemoryFilesPanelStoryPath = 'frontend/src/features/claude-code/components/ClaudeCodeMemoryFilesPanel.stories.tsx';
const claudeCodeSettingsScopeStackStoryPath = 'frontend/src/features/claude-code/components/ClaudeCodeSettingsScopeStack.stories.tsx';
const claudeCodeSubagentCatalogStorybookTitle = 'Design System/业务组件/Claude Code Subagent Catalog';
const claudeCodeMemoryFilesPanelStorybookTitle = 'Design System/业务组件/Claude Code Memory Files Panel';
const claudeCodeSettingsScopeStackStorybookTitle = 'Design System/业务组件/Claude Code Settings Scope Stack';
const codexRouteProbeStoryPath = 'frontend/src/features/codex/components/CodexRouteProbeCard.stories.tsx';
const codexRouteProbeStorybookTitle = 'Design System/业务组件/Codex 路由探测';
const codexAccountDetailStoryPath = 'frontend/src/features/codex/components/CodexAccountDetailComponents.stories.tsx';
const codexAccountDetailStorybookTitle = 'Design System/业务组件/Codex 账号详情';
const codexAccountOrderStoryPath = 'frontend/src/features/codex/components/CodexAccountOrderComponents.stories.tsx';
const codexAccountOrderStorybookTitle = 'Design System/业务组件/Codex 账号顺序';
const codexLiveSessionsStoryPath = 'frontend/src/features/codex-live-sessions/components/CodexLiveSessionsComponents.stories.tsx';
const codexLiveSessionsStorybookTitle = 'Design System/业务组件/Codex 运行会话';

export const designSystemComponentManifest = [
  {
    id: 'accounts-account-card',
    componentName: 'AccountCard',
    sourcePath: 'frontend/src/features/accounts/components/AccountCard.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '完整账号卡已通过 Account Cards story 收编，覆盖常规、带额度条的缩略模式、选择、待删除、列表阻断态和已验证模板应用菜单，auth file 下载依赖已由 runtime wrapper 通过 downloadAuthFile prop 注入。',
    matchedPatterns: ['DebugPanel EntryCard'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'compact-quota', 'selection-selected', 'pending-delete', 'list-blocked', 'template-apply-menu'],
    mockDataSources: ['storybook AccountRecord/usage/rate-limit mock', 'storybook downloadAuthFile mock'],
  },
  {
    id: 'accounts-account-card-frame',
    componentName: 'AccountCardFrame',
    sourcePath: 'frontend/src/features/accounts/components/AccountCardFrame.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '可点击卡片外壳已通过 Account Cards story 收编，覆盖默认、选中和嵌套 action 边界。',
    matchedPatterns: ['DesignSystemStoryFrame'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['default', 'interactive-child', 'selected'],
    mockDataSources: ['storybook local mock'],
  },
  {
    id: 'accounts-account-card-skeleton',
    componentName: 'AccountCardSkeleton',
    sourcePath: 'frontend/src/features/accounts/components/AccountCardSkeleton.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号卡骨架屏已通过 Account Cards story 收编，覆盖卡片加载矩阵。',
    matchedPatterns: ['PageLoadingFallback'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['full', 'compact'],
    mockDataSources: ['storybook local mock'],
  },
  {
    id: 'accounts-account-detail-modal-frame',
    componentName: 'AccountDetailModalFrame',
    sourcePath: 'frontend/src/features/accounts/components/AccountDetailModalFrame.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号详情弹窗 shell 已接入通用 ModalFrame，并通过 Account Modals story 收编，覆盖 header、滚动内容、错误条和 footer action。',
    matchedPatterns: ['ModalFrame'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['default', 'long-content'],
    mockDataSources: ['storybook account modal content mock'],
  },
  {
    id: 'accounts-account-detail-primitives',
    componentName: 'AccountDetailPrimitives',
    sourcePath: 'frontend/src/features/accounts/components/AccountDetailPrimitives.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号详情统一设计语言的 section、标准模块头部、density、overview grid、module grid、module card mode、stat grid、field grid、pill、notice、empty state 和 evidence grid primitives，已被账号、OpenAI-compatible、Codex/Claude route 详情复用。',
    matchedPatterns: ['AccountDetailModalFrame'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['section', 'standard-module-header', 'density', 'runtime-evidence-overview', 'module-grid', 'card-mode', 'stat-grid', 'field-grid', 'pill-tones', 'notice', 'empty-state', 'evidence'],
    mockDataSources: ['storybook account detail primitives mock'],
  },
  {
    id: 'accounts-account-curl-editor-modal',
    componentName: 'AccountCurlEditorModal',
    sourcePath: 'frontend/src/features/accounts/components/AccountCurlEditorModal.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号详情 quota/billing curl 编辑弹窗已拆成无 Wails 的 modal 组件，并通过 Account Modals story 覆盖脚本编辑、变量插入、取消和提交状态。',
    matchedPatterns: ['AccountDetailModalFrame', 'SnippetEditor', 'VariableTokenList'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['quota-script', 'billing-script', 'dirty-draft', 'submitting'],
    mockDataSources: ['storybook account detail curl editor mock'],
  },
  {
    id: 'accounts-account-detail-sections',
    componentName: 'AccountDetailSections',
    sourcePath: 'frontend/src/features/accounts/components/AccountDetailSections.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '统一账号详情页的 header、credentials、verify、quota、billing、module layout、card mode 和 footer 已拆成无 Wails 的 section 组件；Quota/Billing 编辑模块在 card mode 中并排展示，并通过 Account Modals story 收编。',
    matchedPatterns: ['AccountDetailModalFrame', 'Combobox', 'ToggleSwitch'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'quota-billing-side-by-side', 'standard-module-header', 'module-layout', 'card-mode', 'missing-fields', 'saving-footer', 'live-billing'],
    mockDataSources: ['storybook AccountRecord/usage/verify/billing mock', 'storybook quota and billing test callbacks'],
  },
  {
    id: 'accounts-account-group-section',
    componentName: 'AccountGroupSection',
    sourcePath: 'frontend/src/features/accounts/components/AccountGroupSection.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号分组业务 wrapper 已将 auth file 下载函数改为 prop 注入，并通过 Account Group Sections story 收编真实 AccountCard 组合态。',
    matchedPatterns: ['DebugPanel grouped list'],
    storyPath: accountGroupSectionStoryPath,
    storybookTitle: accountGroupSectionStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['runtime-wrapper', 'selection-list'],
    mockDataSources: ['storybook account group, usage, rate-limit and downloadAuthFile mock'],
  },
  {
    id: 'accounts-account-group-section-view',
    componentName: 'AccountGroupSectionView',
    sourcePath: 'frontend/src/features/accounts/components/AccountGroupSectionView.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号分组标题和响应式卡片网格已拆成无 Wails 的纯 view，并通过 Account Group Sections story 收编。',
    matchedPatterns: ['DebugPanel grouped list', 'AccountCardFrame'],
    storyPath: accountGroupSectionStoryPath,
    storybookTitle: accountGroupSectionStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['full-grid', 'compact-grid', 'list', 'empty'],
    mockDataSources: ['storybook account group and mock card renderer'],
  },
  {
    id: 'accounts-account-health-bar',
    componentName: 'AccountHealthBar',
    sourcePath: 'frontend/src/features/accounts/components/AccountHealthBar.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号健康条已通过 Account Cards story 收编，覆盖健康、混合失败和空闲块。',
    matchedPatterns: ['DebugPanel status card'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['healthy', 'warning', 'failed'],
    mockDataSources: ['storybook AccountUsageSummary mock'],
  },
  {
    id: 'accounts-local-cli-apply-confirm',
    componentName: 'AccountLocalCliApplyConfirm',
    sourcePath: 'frontend/src/features/accounts/components/AccountLocalCliApplyConfirm.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号模板本地 CLI 应用确认页已按文件预览器布局实现，复用 ModalFrame 与 StatusSnippetPanel；deep link 账号导入已拆到独立批量确认页，不再复用本地 CLI 写入草稿。',
    matchedPatterns: ['ModalFrame', 'StatusSnippetPanel', 'SnippetPre'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['codex-api-key', 'codex-oauth-preserve', 'claude-code', 'blocking-warning', 'preview-only'],
    mockDataSources: ['storybook AccountCliApplyDraft/relay key mock', 'browser preview runtime fallback'],
  },
  {
    id: 'accounts-deep-link-account-import-confirm',
    componentName: 'DeepLinkAccountImportConfirm',
    sourcePath: 'frontend/src/features/accounts/components/DeepLinkAccountImportConfirm.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'gt deep link 一期只做批量账号导入，使用独立确认页展示来源、红线脱敏 URL、账号摘要和逐账号 apply 结果，不再写 Codex local config。',
    matchedPatterns: ['ModalFrame', 'batch account preview', 'redacted deep link URL'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['preview', 'applying', 'partial-result', 'failed-result', 'preview-only'],
    mockDataSources: ['DeepLinkImportPreview', 'DeepLinkApplyResult'],
  },
  {
    id: 'accounts-account-proxy-route-section',
    componentName: 'AccountProxyRouteSection',
    sourcePath: 'frontend/src/features/accounts/components/AccountProxyRouteSection.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号代理出口选择区块已支持注入 proxy nodes，并通过 Account Proxy Route story 收编。',
    matchedPatterns: ['SegmentedControl', 'Combobox'],
    storyPath: accountProxyRouteStoryPath,
    storybookTitle: accountProxyRouteStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['inherit', 'direct', 'custom', 'detached-current-url', 'no-nodes', 'readonly'],
    mockDataSources: ['storybook injected proxy node mock'],
  },
  {
    id: 'accounts-account-rotation-modal',
    componentName: 'AccountRotationModal',
    sourcePath: 'frontend/src/features/accounts/components/AccountRotationModal.tsx',
    ownerFeature: 'accounts',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '依赖 useAccountRotation 加载/保存真实配置，不直接进入 Storybook；先拆纯 view。',
    matchedPatterns: ['ToggleSwitch', 'SegmentedControl'],
    suggestedDesignComponent: 'RotationSettingsDialog',
    revisitTrigger: '轮换 modal 拆出纯展示层后复查。',
  },
  {
    id: 'accounts-accounts-header',
    componentName: 'AccountsHeader',
    sourcePath: 'frontend/src/features/accounts/components/AccountsHeader.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号页头已通过 Accounts Header story 收编，覆盖默认、刷新中、菜单展开、未就绪和统一新增入口。',
    matchedPatterns: ['WorkspacePageHeader'],
    storyPath: accountsHeaderStoryPath,
    storybookTitle: accountsHeaderStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['default', 'loading', 'menu-open', 'not-ready', 'unified-compose'],
    mockDataSources: ['storybook accounts header refs and callbacks mock'],
  },
  {
    id: 'accounts-accounts-toolbar',
    componentName: 'AccountsToolbar',
    sourcePath: 'frontend/src/features/accounts/components/AccountsToolbar.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号工作台搜索、来源筛选、状态筛选、密度切换和批量选择工具栏已通过 Accounts Toolbar story 收编。',
    matchedPatterns: ['SegmentedControl'],
    storyPath: accountsToolbarStoryPath,
    storybookTitle: accountsToolbarStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['default', 'filters-open', 'source-filter', 'status-filter', 'empty-selection', 'bulk-selection'],
    mockDataSources: ['storybook account toolbar filters/search/display mode/selection mock'],
  },
  {
    id: 'accounts-list-workbench-view',
    componentName: 'AccountsListWorkbenchView',
    sourcePath: 'frontend/src/features/accounts/components/AccountsListWorkbenchView.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号列表整体已拆成无 Wails 的组合 view，并通过 Accounts List story 收编页头、工具栏、分组和账号卡片联动状态。',
    matchedPatterns: ['WorkspacePageHeader', 'SegmentedControl', 'AccountCardFrame'],
    storyPath: accountsListStoryPath,
    storybookTitle: accountsListStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['full-list', 'compact-list', 'selection-list', 'filtered-empty'],
    mockDataSources: ['storybook account groups, account cards, filters, display mode and selection mock'],
  },
  {
    id: 'accounts-api-key-compose-modal',
    componentName: 'ApiKeyComposeModal',
    sourcePath: 'frontend/src/features/accounts/components/ApiKeyComposeModal.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '新增 API key 弹窗已通过 Account Modals story 收编，覆盖空表单、已填 quota、模型拉取中和验证错误。',
    matchedPatterns: ['Combobox'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['empty', 'filled-quota', 'fetching-models', 'verify-error'],
    mockDataSources: ['storybook api key compose form mock', 'storybook probe callback mock'],
  },
  {
    id: 'accounts-api-key-detail-modal',
    componentName: 'ApiKeyDetailModal',
    sourcePath: 'frontend/src/features/accounts/components/ApiKeyDetailModal.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'API key 详情弹窗已将 rate-limit CRUD 改为可注入 API，并通过 Account Modals story 收编配置、验证、quota curl 和限流区块。',
    matchedPatterns: ['Combobox', 'ToggleSwitch', 'DebugPanel details'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['verify-success', 'verify-error', 'quota-curl', 'rate-limit-rules'],
    mockDataSources: ['storybook AccountRecord/usage/rate-limit mock', 'storybook quota and rate-limit API mock'],
  },
  {
    id: 'accounts-attribution-card',
    componentName: 'AttributionCard',
    sourcePath: 'frontend/src/features/accounts/components/AttributionCard.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '归因卡已通过 Account Cards story 收编，覆盖健康、失败、带额度条的紧凑模式和列表密度。',
    matchedPatterns: ['DebugPanel EntryCard'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['healthy', 'limited', 'failed', 'compact-quota', 'long-content'],
    mockDataSources: ['storybook AccountUsageSummary mock', 'storybook quota/billing/rate-limit mock'],
  },
  {
    id: 'accounts-card-sections',
    componentName: 'CardSections',
    sourcePath: 'frontend/src/features/accounts/components/CardSections.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号卡片指标段已通过 Account Cards story 收编，覆盖 traffic、mini metrics、usage、quota、quota 内部刷新骨架、billing 和 rate-limit；evidence 已降级到详情页诊断区。',
    matchedPatterns: ['DebugPanel state matrix'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['traffic', 'mini-metrics', 'usage', 'quota', 'quota-refreshing', 'billing', 'rate-limit'],
    mockDataSources: ['storybook traffic/quota/billing/usage/rate-limit mock'],
  },
  {
    id: 'accounts-codex-oauth-modal',
    componentName: 'CodexOAuthModal',
    sourcePath: 'frontend/src/features/accounts/components/CodexOAuthModal.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'OAuth URL 弹窗已通过 Account Modals story 收编，复制动作可用 mock handler 隔离，覆盖 ready、existing account 和 copy error。',
    matchedPatterns: ['DebugPanel empty/state'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'existing-copy-success', 'copy-error'],
    mockDataSources: ['storybook oauth url and copy state mock'],
  },
  {
    id: 'accounts-openai-compatible-compose-modal',
    componentName: 'OpenAICompatibleComposeModal',
    sourcePath: 'frontend/src/features/accounts/components/OpenAICompatibleComposeModal.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'OpenAI-compatible provider 新增表单已通过 OpenAI Compatible story 收编，覆盖空表单、preset selected 和校验错误。',
    matchedPatterns: ['ActionSelect'],
    storyPath: openAICompatibleStoryPath,
    storybookTitle: openAICompatibleStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['empty', 'preset-selected', 'validation-error'],
    mockDataSources: ['storybook openai-compatible compose form mock'],
  },
  {
    id: 'accounts-openai-compatible-detail-modal',
    componentName: 'OpenAICompatibleDetailModal',
    sourcePath: 'frontend/src/features/accounts/components/OpenAICompatibleDetailModal.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'OpenAI-compatible 完整详情弹窗已通过 RateLimitRulesAPI mock 隔离规则 CRUD，并在 OpenAI Compatible story 收编，接入账号详情统一卡片布局和页脚保存。',
    matchedPatterns: ['Combobox', 'ToggleSwitch'],
    storyPath: openAICompatibleStoryPath,
    storybookTitle: openAICompatibleStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['rate-limit-composed', 'footer-save'],
    mockDataSources: ['storybook provider detail draft', 'storybook rate-limit status and CRUD API mock'],
  },
  {
    id: 'accounts-openai-compatible-detail-panel',
    componentName: 'OpenAICompatibleDetailPanel',
    sourcePath: 'frontend/src/features/accounts/components/OpenAICompatibleDetailPanel.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'OpenAI-compatible 详情主体已拆成无 Wails 展示层，并通过 AccountDetailBody 与 section density 纳入账号详情统一模块布局。',
    matchedPatterns: ['AccountDetailModalFrame', 'AccountDetailSection', 'ActionSelect'],
    storyPath: openAICompatibleStoryPath,
    storybookTitle: openAICompatibleStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready-remote-models', 'card-mode', 'validation-error', 'fetching-models', 'footer-save'],
    mockDataSources: ['storybook provider draft, verify state, remote model state'],
  },
  {
    id: 'accounts-openai-compatible-provider-card',
    componentName: 'OpenAICompatibleProviderCard',
    sourcePath: 'frontend/src/features/accounts/components/OpenAICompatibleProviderCard.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'OpenAI-compatible provider 卡片已通过 OpenAI Compatible story 收编，覆盖验证成功、验证错误、禁用、pending 和 rate-limit blocked。',
    matchedPatterns: ['DebugPanel EntryCard'],
    storyPath: openAICompatibleStoryPath,
    storybookTitle: openAICompatibleStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'error', 'disabled', 'pending', 'rate-limit-blocked'],
    mockDataSources: ['storybook openai-compatible provider/verify/usage/rate-limit mock'],
  },
  {
    id: 'accounts-openai-compatible-workspace',
    componentName: 'OpenAICompatibleWorkspace',
    sourcePath: 'frontend/src/features/accounts/components/OpenAICompatibleWorkspace.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'OpenAI-compatible workspace 已通过 OpenAI Compatible story 收编，覆盖 loading、empty、grid 和 embedded 组合态。',
    matchedPatterns: ['WorkspacePageHeader', 'PageLoadingFallback'],
    storyPath: openAICompatibleStoryPath,
    storybookTitle: openAICompatibleStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['loading', 'empty', 'grid', 'embedded'],
    mockDataSources: ['storybook openai-compatible provider/verify/remote-models mock'],
  },
  {
    id: 'accounts-account-import-modal',
    componentName: 'AccountImportModal',
    sourcePath: 'frontend/src/features/accounts/components/AccountImportModal.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '统一导入弹窗已通过 Account Modals story 收编，覆盖空队列、粘贴 JSON 数组和混合候选队列状态。',
    matchedPatterns: ['ModalFrame', 'input-swiss', 'btn-swiss'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['empty', 'paste-array', 'queued'],
    mockDataSources: ['storybook account import file/paste payload mock'],
  },
  {
    id: 'accounts-rate-limit-rules-section',
    componentName: 'RateLimitRulesSection',
    sourcePath: 'frontend/src/features/accounts/components/RateLimitRulesSection.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '路由守卫规则编辑区块已通过可注入 RateLimitRulesAPI 隔离运行时 CRUD，并通过 Rate Limit Rules story 收编。',
    matchedPatterns: ['ToggleSwitch'],
    storyPath: rateLimitRulesStoryPath,
    storybookTitle: rateLimitRulesStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['active-rules', 'empty-rules', 'preview-fallback'],
    mockDataSources: ['storybook rate limit status and CRUD API mock'],
  },
  {
    id: 'accounts-unified-account-detail-modal',
    componentName: 'UnifiedAccountDetailModal',
    sourcePath: 'frontend/src/features/accounts/components/UnifiedAccountDetailModal.tsx',
    ownerFeature: 'accounts',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '直接调用 auth file 下载、模型读取和内容清洗，不直接进入设计系统。',
    matchedPatterns: ['Combobox', 'ToggleSwitch'],
    suggestedDesignComponent: 'AccountDetailWorkbench',
    revisitTrigger: '拆出无 Wails sections 后复查。',
  },
  {
    id: 'accounts-unified-compose-modal',
    componentName: 'UnifiedComposeModal',
    sourcePath: 'frontend/src/features/accounts/components/UnifiedComposeModal.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '统一新增账号两步弹窗已通过 Account Modals story 收编，覆盖 preset list、provider form step 和 validation error。',
    matchedPatterns: ['ActionSelect'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['preset-list', 'form-step', 'error'],
    mockDataSources: ['storybook unified compose form and vendor preset mock'],
  },
  {
    id: 'accounts-vendor-logo-mark',
    componentName: 'VendorLogoMark',
    sourcePath: 'frontend/src/features/accounts/components/VendorLogoMark.tsx',
    ownerFeature: 'accounts',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '统一新增弹窗和 provider 卡片复用的品牌徽记 helper，不单独承接 Storybook，但作为可复用视觉锚点应纳入 manifest。',
    matchedPatterns: ['InlineBrandMark'],
    revisitTrigger: '若后续需要单独调整品牌徽记尺寸、色板或无图标兜底时再收编。',
  },
  {
    id: 'accounts-rotation-config-section',
    componentName: 'RotationConfigSection',
    sourcePath: 'frontend/src/features/accounts/components/account-rotation/RotationConfigSection.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号轮换 routing 配置表单已通过 Account Rotation story 收编，覆盖默认值和策略菜单展开态。',
    matchedPatterns: ['Combobox', 'ToggleSwitch'],
    storyPath: accountRotationStoryPath,
    storybookTitle: accountRotationStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['priority', 'random', 'disabled'],
    mockDataSources: ['storybook relay routing draft mock'],
  },
  {
    id: 'accounts-rotation-priority-item',
    componentName: 'RotationPriorityItem',
    sourcePath: 'frontend/src/features/accounts/components/account-rotation/RotationPriorityItem.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号轮换优先级项已通过 Account Rotation story 收编，覆盖普通、拖拽、pending 和 disabled 账号状态。',
    matchedPatterns: ['DebugPanel EntryCard'],
    storyPath: accountRotationStoryPath,
    storybookTitle: accountRotationStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['normal', 'dragging', 'disabled'],
    mockDataSources: ['storybook AccountRecord rotation mock'],
  },
  {
    id: 'accounts-usage-desk-chart',
    componentName: 'UsageDeskChart',
    sourcePath: 'frontend/src/features/accounts/components/usage-desk/UsageDeskChart.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Usage Desk 图表已通过 Usage Desk story 收编，覆盖双曲线、选中点、控件区和空态。',
    matchedPatterns: ['DebugPanel state matrix'],
    storyPath: usageDeskStoryPath,
    storybookTitle: usageDeskStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['observed', 'projected', 'empty'],
    mockDataSources: ['storybook usage chart point mock'],
  },
  {
    id: 'accounts-usage-desk-panels',
    componentName: 'UsageDeskPanels',
    sourcePath: 'frontend/src/features/accounts/components/usage-desk/UsageDeskPanels.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Usage Desk 信息面板和 session drilldown 已通过 Usage Desk story 收编，覆盖 totals、session rows 和空会话。',
    matchedPatterns: ['DebugPanel Empty', 'DebugPanel EntryCard'],
    storyPath: usageDeskStoryPath,
    storybookTitle: usageDeskStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['totals', 'session-drilldown', 'empty'],
    mockDataSources: ['storybook usage session mock'],
  },
  {
    id: 'accounts-usage-detail-table',
    componentName: 'UsageDetailTable',
    sourcePath: 'frontend/src/features/accounts/components/usage-desk/UsageDetailTable.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Usage 明细表已通过 Usage Desk story 收编，覆盖 projected columns、选中行和空表。',
    matchedPatterns: ['DebugPanel log table'],
    storyPath: usageDeskStoryPath,
    storybookTitle: usageDeskStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['daily', 'selected', 'empty'],
    mockDataSources: ['storybook usage minute row mock'],
  },
  {
    id: 'codex-binary-summary-panel',
    componentName: 'CodexBinarySummaryPanel',
    sourcePath: 'frontend/src/features/codex-binary/components/CodexBinarySummaryPanel.tsx',
    ownerFeature: 'codex-binary',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '运行时版本摘要已通过 Codex Binary story 收编，覆盖托管 PATH、doctor error 和刷新动作。',
    matchedPatterns: ['WorkspacePageHeader'],
    storyPath: codexBinaryStoryPath,
    storybookTitle: codexBinaryStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['managed-path-disabled', 'managed-path-enabled', 'doctor-error'],
    mockDataSources: ['codexBinaryPreviewSnapshot'],
  },
  {
    id: 'codex-binary-version-cell',
    componentName: 'CodexBinaryVersionCell',
    sourcePath: 'frontend/src/features/codex-binary/components/CodexBinaryVersionCell.tsx',
    ownerFeature: 'codex-binary',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '可展开版本行已通过 Codex Binary story 收编，覆盖 active/download/expanded release notes。',
    matchedPatterns: ['ActionSelect', 'DebugPanel details'],
    storyPath: codexBinaryStoryPath,
    storybookTitle: codexBinaryStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['active', 'downloadable', 'expanded-notes'],
    mockDataSources: ['codexBinaryPreviewSnapshot', 'codexBinaryPreviewNotes'],
  },
  {
    id: 'codex-binary-version-list',
    componentName: 'CodexBinaryVersionList',
    sourcePath: 'frontend/src/features/codex-binary/components/CodexBinaryVersionList.tsx',
    ownerFeature: 'codex-binary',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '版本列表已通过 Codex Binary story 收编，覆盖筛选、展开行和空态。',
    matchedPatterns: ['SegmentedControl', 'DebugPanel list'],
    storyPath: codexBinaryStoryPath,
    storybookTitle: codexBinaryStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['stable-filter', 'all-filter', 'empty'],
    mockDataSources: ['codexBinaryPreviewSnapshot'],
  },
  {
    id: 'settings-release-panel',
    componentName: 'SettingsReleasePanel',
    sourcePath: 'frontend/src/features/settings/components/SettingsReleasePanel.tsx',
    ownerFeature: 'settings',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '设置页版本更新区块已拆成无 Wails 的纯展示组件，并展示当前项目构建 git hash；Storybook 覆盖可更新、检查中和原生更新三种状态。',
    matchedPatterns: ['WorkspacePageHeader', 'SegmentedControl', 'ToggleSwitch'],
    storyPath: settingsReleasePanelStoryPath,
    storybookTitle: settingsReleasePanelStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'checking', 'native-updater', 'git-hash'],
    mockDataSources: ['storybook settings release/version/git hash mock'],
  },
  {
    id: 'channel-routing-workbench',
    componentName: 'ChannelRoutingWorkbench',
    sourcePath: 'frontend/src/features/channel-routing/components/ChannelRoutingWorkbench.tsx',
    ownerFeature: 'channel-routing',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: 'Account Routing Engine 的跨渠道路由控制面，先随 Codex/Claude account-list 页面进入业务验收；后续补独立 story 覆盖三模式、preview explain、保存中和空候选状态。',
    matchedPatterns: ['SegmentedControl', 'DebugPanel summary', 'WorkspacePageHeader'],
    suggestedDesignComponent: 'RoutingPolicyWorkbench',
    revisitTrigger: 'Codex/Claude Channel Routing 页面稳定后补 story matrix。',
  },
  {
    id: 'claude-code-account-list-workbench',
    componentName: 'ClaudeCodeAccountListWorkbench',
    sourcePath: 'frontend/src/features/claude-code/components/ClaudeCodeAccountListWorkbench.tsx',
    ownerFeature: 'claude-code',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Claude Code 账号列表业务工作台已通过 Claude Code Account List story 收编，覆盖 Anthropic 格式筛选、请求顺序、官方默认 profile、模型映射草稿、禁用阻塞和路由探测 mock。',
    matchedPatterns: ['CodexAccountOrderSection', 'CodexRouteProbeCard', 'WorkspacePageHeader'],
    storyPath: claudeCodeAccountListStoryPath,
    storybookTitle: claudeCodeAccountListStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'source-conflict', 'disabled-blocked', 'profile-draft'],
    mockDataSources: ['storybook claude code account rows/profile/mapping/probe mock'],
  },
  {
    id: 'claude-code-asset-workbench',
    componentName: 'ClaudeCodeAssetWorkbench',
    sourcePath: 'frontend/src/features/claude-code/components/ClaudeCodeAssetWorkbench.tsx',
    ownerFeature: 'claude-code',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Claude Code 资产工作台纯展示层已进入设计系统，覆盖 Skills、legacy commands、MCP scope precedence、secret redaction、parse error、empty 和 preservative patch preview；后端 adapter 接入前必须先通过该状态矩阵。',
    matchedPatterns: ['CodexExtensionsFeature', 'WorkspacePageHeader', 'SegmentedControl', 'SnippetPre', 'ModalFrame'],
    storyPath: claudeCodeAssetWorkbenchStoryPath,
    storybookTitle: claudeCodeAssetWorkbenchStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['skills-ready', 'skills-legacy-command', 'mcp-ready', 'mcp-shadowed-scope', 'empty', 'parse-error', 'saving-diff'],
    mockDataSources: ['storybook claude code skills/mcp/scope/diff/candidate mock'],
  },
  {
    id: 'claude-code-settings-scope-stack',
    componentName: 'ClaudeCodeSettingsScopeStack',
    sourcePath: 'frontend/src/features/claude-code/components/ClaudeCodeSettingsScopeStack.tsx',
    ownerFeature: 'claude-code',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Claude Code Settings scope stack 已进入设计系统，覆盖 user/project/local/managed 四个 scope layer 的手风琴展示，支持 parse error、editing 和 saving-diff 状态。',
    matchedPatterns: ['AssetWorkbenchShell', 'WorkspacePageHeader', 'SnippetPre'],
    storyPath: claudeCodeSettingsScopeStackStoryPath,
    storybookTitle: claudeCodeSettingsScopeStackStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['all-layers-valid', 'partial-layers', 'parse-error', 'managed-readonly', 'env-field-editing', 'all-layers-empty', 'saving-diff'],
    mockDataSources: ['storybook claude code settings layer/scopes mock'],
  },
  {
    id: 'codex-account-detail-modal',
    componentName: 'CodexAccountDetailModal',
    sourcePath: 'frontend/src/features/codex/components/CodexAccountDetailModal.tsx',
    ownerFeature: 'codex',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex 账号详情 story 已移除旧状态矩阵，先收敛为一个桌面新版草稿，用于调整 OpenAI-compatible 详情的信息密度、凭据验证、路由、额度、余额和模型映射布局。',
    matchedPatterns: ['AccountDetailModalFrame', 'AccountDetailSection', 'Combobox'],
    storyPath: codexAccountDetailStoryPath,
    storybookTitle: codexAccountDetailStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['desktop-draft'],
    mockDataSources: ['storybook DeepSeek openai-compatible account row, quota, billing, verify, model mapping mock'],
  },
  {
    id: 'codex-account-list-view',
    componentName: 'CodexAccountListView',
    sourcePath: 'frontend/src/features/codex/components/CodexAccountListView.tsx',
    ownerFeature: 'codex',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '组合整个 account-list workspace，先收编下层 row/section/probe 组件。',
    matchedPatterns: ['WorkspacePageHeader', 'PageLoadingFallback'],
    suggestedDesignComponent: 'AccountListWorkspaceView',
    revisitTrigger: 'CodexAccountOrderRow/Section 和 ProbeCard 已有 stories 后复查。',
  },
  {
    id: 'codex-account-order-row',
    componentName: 'CodexAccountOrderRow',
    sourcePath: 'frontend/src/features/codex/components/CodexAccountOrderRow.tsx',
    ownerFeature: 'codex',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex 账号请求顺序行已通过 Codex Account Order story 收编，覆盖 full/compact/list、拖拽、probe hit、policy skipped、disabled 和 rate-limit blocked。',
    matchedPatterns: ['ToggleSwitch', 'DebugPanel EntryCard'],
    storyPath: codexAccountOrderStoryPath,
    storybookTitle: codexAccountOrderStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['full', 'compact', 'list', 'dragged', 'probe-hit', 'policy-skipped', 'disabled', 'rate-limit-blocked'],
    mockDataSources: ['storybook codex account row/policy/quota/usage/rate-limit mock'],
  },
  {
    id: 'codex-account-order-section',
    componentName: 'CodexAccountOrderSection',
    sourcePath: 'frontend/src/features/codex/components/CodexAccountOrderSection.tsx',
    ownerFeature: 'codex',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex 请求顺序列表容器已通过 Codex Account Order story 收编，覆盖密度、未保存、保存中、等待、加载和空列表。',
    matchedPatterns: ['SegmentedControl', 'DebugPanel list'],
    storyPath: codexAccountOrderStoryPath,
    storybookTitle: codexAccountOrderStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['compact', 'full-unsaved', 'list-saving', 'waiting', 'loading', 'empty'],
    mockDataSources: ['storybook codex account section rows/policy/quota/usage/rate-limit mock'],
  },
  {
    id: 'codex-route-probe-card',
    componentName: 'CodexRouteProbeCard',
    sourcePath: 'frontend/src/features/codex/components/CodexRouteProbeCard.tsx',
    ownerFeature: 'codex',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex 路由探测工作台已通过 Codex Route Probe story 收编，覆盖 idle、running、fallback 和空候选队列。',
    matchedPatterns: ['ToggleSwitch', 'Combobox', 'DebugPanel'],
    storyPath: codexRouteProbeStoryPath,
    storybookTitle: codexRouteProbeStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['idle', 'running', 'failed'],
    mockDataSources: ['storybook codex route probe row/log mock'],
  },
  {
    id: 'codex-live-sessions-workbench',
    componentName: 'CodexLiveSessionsWorkbench',
    sourcePath: 'frontend/src/features/codex-live-sessions/components/CodexLiveSessionsWorkbench.tsx',
    ownerFeature: 'codex-live-sessions',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex 运行会话纯展示工作台已通过 mock snapshot 纳入设计系统，覆盖 active websocket、reconnecting、degraded_http、failed、empty、high-volume、rate/time metrics 和 redacted diagnostic。',
    matchedPatterns: ['WorkspacePageHeader', 'SearchInput', 'Filter menu', 'SnippetPre', 'DebugPanel list'],
    storyPath: codexLiveSessionsStoryPath,
    storybookTitle: codexLiveSessionsStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['overview', 'active-websocket', 'reconnecting', 'degraded-http', 'failed', 'rate-time-metrics', 'empty', 'high-volume', 'redacted-diagnostic'],
    mockDataSources: ['codexLiveSessionsPreviewSnapshot', 'codexLiveSessionsHighVolumeSnapshot'],
  },
  {
    id: 'codex-live-session-detail',
    componentName: 'SessionDetail',
    sourcePath: 'frontend/src/features/codex-live-sessions/components/CodexLiveSessionDetail.tsx',
    ownerFeature: 'codex-live-sessions',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex 运行会话详情面板已随 CodexLiveSessionsWorkbench story 收编，覆盖空详情、transport lane、timing metrics、request meta、timeline 和 redacted diagnostic。',
    matchedPatterns: ['SnippetPre', 'DebugPanel detail'],
    storyPath: codexLiveSessionsStoryPath,
    storybookTitle: codexLiveSessionsStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['empty-detail', 'transport-lane', 'timing-metrics', 'timeline', 'redacted-diagnostic'],
    mockDataSources: ['codexLiveSessionsPreviewSnapshot', 'codexLiveSessionsHighVolumeSnapshot'],
  },
  {
    id: 'codex-live-session-feed',
    componentName: 'SessionFeed',
    sourcePath: 'frontend/src/features/codex-live-sessions/components/CodexLiveSessionFeed.tsx',
    ownerFeature: 'codex-live-sessions',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex 运行会话 feed 窄列列表已随 CodexLiveSessionsWorkbench story 收编，覆盖 active、degraded、empty、selected row 和 high-volume rows。',
    matchedPatterns: ['DebugPanel list', 'SearchInput'],
    storyPath: codexLiveSessionsStoryPath,
    storybookTitle: codexLiveSessionsStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['active', 'degraded', 'empty', 'selected', 'high-volume'],
    mockDataSources: ['codexLiveSessionsPreviewSnapshot', 'codexLiveSessionsHighVolumeSnapshot'],
  },
  {
    id: 'codex-live-session-source-badge',
    componentName: 'SourceBadge',
    sourcePath: 'frontend/src/features/codex-live-sessions/components/CodexLiveSessionSummary.tsx',
    ownerFeature: 'codex-live-sessions',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex 运行会话 source badge 已随 CodexLiveSessionsWorkbench story 收编，覆盖 live、cache/unavailable、empty 和 high-volume 来源标记。',
    matchedPatterns: ['DebugPanel source badge'],
    storyPath: codexLiveSessionsStoryPath,
    storybookTitle: codexLiveSessionsStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['live', 'cache', 'unavailable'],
    mockDataSources: ['codexLiveSessionsPreviewSnapshot', 'codexLiveSessionsHighVolumeSnapshot'],
  },
  {
    id: 'session-plugin-console-panel',
    componentName: 'SessionPluginConsolePanel',
    sourcePath: 'frontend/src/features/session-management/components/SessionPluginConsolePanel.tsx',
    ownerFeature: 'session-management',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '会话插件控制台已从 space HTML 设计稿收编为纯展示组件，覆盖插件注册表、作用域选择、执行状态、会话选择、队列和插件输出，作为 session-management 插件宿主的设计系统基准。',
    matchedPatterns: ['DesignSystemStoryFrame', 'WorkspacePageHeader', 'DebugPanel grouped list'],
    previewPath: 'frontend/src/features/design-system/businessComponentPreviews.tsx',
    previewTitle: '5173/业务组件/会话插件控制台',
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'running', 'done', 'scope-project', 'queue', 'analysis-result'],
    mockDataSources: ['5173 businessComponentPreviews session-management plugin/analysis/session mock'],
  },
  {
    id: 'codex-model-combobox',
    componentName: 'ModelCombobox',
    sourcePath: 'frontend/src/features/codex/components/ModelCombobox.tsx',
    ownerFeature: 'codex',
    status: 'excluded',
    tier: 'feature-component',
    decisionReason: '只是 Combobox 的 Codex 模型薄包装，设计系统价值并入基础 Combobox，不单独收编。',
    matchedPatterns: ['Combobox'],
    suggestedDesignComponent: 'Combobox',
  },
  {
    id: 'debug-empty-state',
    componentName: 'DebugEmptyState',
    sourcePath: 'frontend/src/features/debug/components/DebugEmptyState.tsx',
    ownerFeature: 'debug',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '调试面板空状态已通过 Debug Panel story 收编。',
    matchedPatterns: ['DebugPanel Empty'],
    storyPath: debugPanelStoryPath,
    storybookTitle: debugPanelStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['empty'],
    mockDataSources: ['storybook local mock'],
  },
  {
    id: 'debug-entry-card',
    componentName: 'DebugEntryCard',
    sourcePath: 'frontend/src/features/debug/components/DebugEntryCard.tsx',
    ownerFeature: 'debug',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '调试日志卡片已通过 Debug Panel story 收编，覆盖成功、错误、折叠和选中状态。',
    matchedPatterns: ['DebugPanel EntryCard'],
    storyPath: debugPanelStoryPath,
    storybookTitle: debugPanelStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['success', 'error', 'collapsed', 'selected'],
    mockDataSources: ['storybook request/response mock'],
  },
  {
    id: 'debug-header',
    componentName: 'DebugHeader',
    sourcePath: 'frontend/src/features/debug/components/DebugHeader.tsx',
    ownerFeature: 'debug',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '调试面板工具栏已通过 Debug Panel story 收编。',
    matchedPatterns: ['DebugPanel toolbar'],
    storyPath: debugPanelStoryPath,
    storybookTitle: debugPanelStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['default', 'all-selected', 'copy-success'],
    mockDataSources: ['storybook local mock'],
  },
  {
    id: 'status-relay-editors',
    componentName: 'RelayEditors',
    sourcePath: 'frontend/src/features/status/components/RelayEditors.tsx',
    ownerFeature: 'status',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Relay key/provider/model editor modals 已通过 Status Relay Editors story 收编，覆盖创建、重命名、错误和模型输入状态。',
    matchedPatterns: ['DesignSystemStoryFrame'],
    storyPath: statusRelayEditorsStoryPath,
    storybookTitle: statusRelayEditorsStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['key-editor', 'provider-editor', 'model-editor'],
    mockDataSources: ['storybook relay editor state mock'],
  },
  {
    id: 'status-codex-config-rows',
    componentName: 'StatusCodexConfigRows',
    sourcePath: 'frontend/src/features/status/components/StatusCodexConfigRows.tsx',
    ownerFeature: 'status',
    status: 'candidate',
    tier: 'feature-component',
    decisionReason: 'Codex root settings 与 model providers 共用的配置行渲染器，已抽出复用但当前由父级 section stories 间接覆盖，后续若暴露独立编辑状态再单独收编。',
    matchedPatterns: ['ToggleSwitch', 'Form field row', 'Grouped settings list'],
    suggestedDesignComponent: 'SettingsConfigRows',
    requiredStates: ['grouped-rows', 'nested-path', 'busy', 'value-editor'],
    mockDataSources: ['codex feature row config mock'],
  },
  {
    id: 'status-codex-features-section',
    componentName: 'StatusCodexFeaturesSection',
    sourcePath: 'frontend/src/features/status/components/StatusCodexFeaturesSection.tsx',
    ownerFeature: 'status',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex feature 配置列表已拆出并通过 Status Codex Features story 收编，覆盖 ready、dirty preview、saving、loading、empty 和 unsupported/readOnly 状态。',
    matchedPatterns: ['ToggleSwitch', 'SegmentedControl', 'DebugPanel list'],
    storyPath: statusCodexFeaturesStoryPath,
    storybookTitle: statusCodexFeaturesStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'dirty-preview', 'saving', 'loading', 'empty', 'unsupported-readonly'],
    mockDataSources: ['storybook codex feature snapshot/rows/preview mock'],
  },
  {
    id: 'status-codex-root-settings-section',
    componentName: 'StatusCodexRootSettingsSection',
    sourcePath: 'frontend/src/features/status/components/StatusCodexRootSettingsSection.tsx',
    ownerFeature: 'status',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex root bool 设置已拆出并通过 Status Codex Root Settings story 收编，覆盖 ready、dirty preview、saving、loading 和 empty 状态。',
    matchedPatterns: ['ToggleSwitch', 'DesignSystemStoryFrame'],
    storyPath: statusCodexRootSettingsStoryPath,
    storybookTitle: statusCodexRootSettingsStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'dirty-preview', 'saving', 'loading', 'empty'],
    mockDataSources: ['storybook codex root settings snapshot/rows/preview mock'],
  },
  {
    id: 'status-codex-model-providers-section',
    componentName: 'StatusCodexModelProvidersSection',
    sourcePath: 'frontend/src/features/status/components/StatusCodexModelProvidersSection.tsx',
    ownerFeature: 'status',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex model providers 面板已拆出并通过 Story 收编，覆盖 ready、dirty preview、saving、loading 和 empty 状态。',
    matchedPatterns: ['ToggleSwitch', 'DesignSystemStoryFrame'],
    storyPath: statusCodexModelProvidersStoryPath,
    storybookTitle: statusCodexModelProvidersStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'dirty-preview', 'saving', 'loading', 'empty'],
    mockDataSources: ['storybook codex model providers snapshot/rows/preview mock'],
  },
  {
    id: 'status-codex-notice-section',
    componentName: 'StatusCodexNoticeSection',
    sourcePath: 'frontend/src/features/status/components/StatusCodexNoticeSection.tsx',
    ownerFeature: 'status',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex notice 提示开关已拆出并通过 Status Codex Notices story 收编，覆盖 ready、dirty preview、saving、loading 和 empty 状态。',
    matchedPatterns: ['ToggleSwitch', 'DesignSystemStoryFrame'],
    storyPath: statusCodexNoticeStoryPath,
    storybookTitle: statusCodexNoticeStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'dirty-preview', 'saving', 'loading', 'empty'],
    mockDataSources: ['storybook codex notice snapshot/rows/preview mock'],
  },
  {
    id: 'status-local-cli-apply-section',
    componentName: 'StatusApplyLocalSection',
    sourcePath: 'frontend/src/features/status/components/StatusPanels.tsx',
    ownerFeature: 'status',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '本地 Codex / Claude Code 配置应用区块已通过 Status Local CLI Apply story 收编，覆盖 ready、blocked、preserve auth、applying 和 Claude ready，手写字段 label 已收敛到 FormField / FieldLabel。',
    matchedPatterns: ['SegmentedControl', 'ActionSelect', 'FormField', 'FieldLabel', 'ToggleSwitch', 'DebugPanel details'],
    storyPath: statusLocalCliApplyStoryPath,
    storybookTitle: statusLocalCliApplyStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['codex-ready', 'codex-blocked', 'codex-preserve-auth', 'codex-applying', 'claude-ready'],
    mockDataSources: ['storybook relay key, endpoint, provider, model, auth state and diff mock'],
  },
  {
    id: 'status-snippet-panel',
    componentName: 'StatusSnippetPanel',
    sourcePath: 'frontend/src/features/status/components/StatusSnippetPanel.tsx',
    ownerFeature: 'status',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Status 配置片段面板已拆成独立组件并通过 Status Snippet Panel story 收编，覆盖普通配置、diff、长行和 header action；pre 容器已收敛到通用 SnippetPre。',
    matchedPatterns: ['SnippetPre', 'DebugPanel details'],
    storyPath: statusSnippetPanelStoryPath,
    storybookTitle: statusSnippetPanelStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['plain', 'diff', 'long-line', 'header-action'],
    mockDataSources: ['storybook local config snippet mock'],
  },
  {
    id: 'claude-code-memory-files-panel',
    componentName: 'ClaudeCodeMemoryFilesPanel',
    sourcePath: 'frontend/src/features/claude-code/components/ClaudeCodeMemoryFilesPanel.tsx',
    ownerFeature: 'claude-code',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Claude Code Memory Files Panel 已进入设计系统，覆盖 user/project/local CLAUDE.md 文件发现、@import 解析、预览、编辑和 save-preview 状态。',
    matchedPatterns: ['AssetWorkbenchShell', 'WorkspacePageHeader', 'SnippetPre'],
    storyPath: claudeCodeMemoryFilesPanelStoryPath,
    storybookTitle: claudeCodeMemoryFilesPanelStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['all-files-present', 'partial-files', 'import-exists', 'import-missing', 'import-recursion', 'local-not-gitignored', 'save-preview', 'empty', 'parse-error', 'import-depth-limit'],
    mockDataSources: ['storybook claude code memory files/imports/scope mock'],
  },
  {
    id: 'claude-code-subagent-catalog',
    componentName: 'ClaudeCodeSubagentCatalog',
    sourcePath: 'frontend/src/features/claude-code/components/ClaudeCodeSubagentCatalog.tsx',
    ownerFeature: 'claude-code',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Claude Code Subagent Catalog 已进入设计系统，覆盖 user/project subagent 扫描、frontmatter 校验、plugin ignored fields、创建/编辑/删除和 saving-agent 状态。',
    matchedPatterns: ['AssetWorkbenchShell', 'WorkspacePageHeader', 'SnippetPre'],
    storyPath: claudeCodeSubagentCatalogStoryPath,
    storybookTitle: claudeCodeSubagentCatalogStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['valid-agents', 'missing-name', 'missing-description', 'plugin-ignored-fields', 'parse-error', 'empty', 'creating-agent', 'saving-agent'],
    mockDataSources: ['storybook claude code subagent frontmatter/scope/plugin mock'],
  },
] as const satisfies readonly DesignSystemComponentManifestEntry[];

export function getAdmittedDesignSystemComponentManifest() {
  return designSystemComponentManifest.filter((entry) => entry.status === 'admitted');
}
