export type DesignSystemComponentStatus = 'admitted' | 'candidate' | 'deferred' | 'excluded';
export type DesignSystemComponentTier = 'feature-component' | 'ui';

export interface DesignSystemComponentManifestEntry {
  id: string;
  componentName: string;
  sourcePath: string;
  ownerFeature: string;
  status: DesignSystemComponentStatus;
  tier: DesignSystemComponentTier;
  decisionReason: string;
  matchedPatterns: readonly string[];
  suggestedDesignComponent?: string;
  storyPath?: string;
  storybookTitle?: string;
  catalogGroupId?: string;
  requiredStates?: readonly string[];
  mockDataSources?: readonly string[];
  revisitTrigger?: string;
}

const debugPanelStoryPath = 'frontend/src/features/debug/components/DebugPanelComponents.stories.tsx';
const debugPanelStorybookTitle = 'Design System/Feature Components/Debug Panel';
const codexBinaryStoryPath = 'frontend/src/features/codex-binary/components/CodexBinaryComponents.stories.tsx';
const codexBinaryStorybookTitle = 'Design System/Feature Components/Codex Binary';
const accountModalStoryPath = 'frontend/src/features/accounts/components/AccountModalComponents.stories.tsx';
const accountModalStorybookTitle = 'Design System/Feature Components/Account Modals';
const accountsHeaderStoryPath = 'frontend/src/features/accounts/components/AccountsHeaderComponents.stories.tsx';
const accountsHeaderStorybookTitle = 'Design System/Feature Components/Accounts Header';
const accountsToolbarStoryPath = 'frontend/src/features/accounts/components/AccountsToolbarComponents.stories.tsx';
const accountsToolbarStorybookTitle = 'Design System/Feature Components/Accounts Toolbar';
const accountsListStoryPath = 'frontend/src/features/accounts/components/AccountsListComponents.stories.tsx';
const accountsListStorybookTitle = 'Design System/Feature Components/Accounts List';
const accountGroupSectionStoryPath = 'frontend/src/features/accounts/components/AccountGroupSectionComponents.stories.tsx';
const accountGroupSectionStorybookTitle = 'Design System/Feature Components/Account Group Sections';
const accountProxyRouteStoryPath = 'frontend/src/features/accounts/components/AccountProxyRouteSection.stories.tsx';
const accountProxyRouteStorybookTitle = 'Design System/Feature Components/Account Proxy Route';
const rateLimitRulesStoryPath = 'frontend/src/features/accounts/components/RateLimitRulesSection.stories.tsx';
const rateLimitRulesStorybookTitle = 'Design System/Feature Components/Rate Limit Rules';
const accountCardStoryPath = 'frontend/src/features/accounts/components/AccountCardComponents.stories.tsx';
const accountCardStorybookTitle = 'Design System/Feature Components/Account Cards';
const openAICompatibleStoryPath = 'frontend/src/features/accounts/components/OpenAICompatibleComponents.stories.tsx';
const openAICompatibleStorybookTitle = 'Design System/Feature Components/OpenAI Compatible';
const accountRotationStoryPath = 'frontend/src/features/accounts/components/account-rotation/AccountRotationComponents.stories.tsx';
const accountRotationStorybookTitle = 'Design System/Feature Components/Account Rotation';
const statusRelayEditorsStoryPath = 'frontend/src/features/status/components/StatusRelayEditors.stories.tsx';
const statusRelayEditorsStorybookTitle = 'Design System/Feature Components/Status Relay Editors';
const statusCodexFeaturesStoryPath = 'frontend/src/features/status/components/StatusCodexFeaturesSection.stories.tsx';
const statusCodexFeaturesStorybookTitle = 'Design System/Feature Components/Status Codex Features';
const statusLocalCliApplyStoryPath = 'frontend/src/features/status/components/StatusLocalCliApplyPanel.stories.tsx';
const statusLocalCliApplyStorybookTitle = 'Design System/Feature Components/Status Local CLI Apply';
const statusSnippetPanelStoryPath = 'frontend/src/features/status/components/StatusSnippetPanel.stories.tsx';
const statusSnippetPanelStorybookTitle = 'Design System/Feature Components/Status Snippet Panel';
const usageDeskStoryPath = 'frontend/src/features/accounts/components/usage-desk/UsageDeskComponents.stories.tsx';
const usageDeskStorybookTitle = 'Design System/Feature Components/Usage Desk';
const codexRouteProbeStoryPath = 'frontend/src/features/codex/components/CodexRouteProbeCard.stories.tsx';
const codexRouteProbeStorybookTitle = 'Design System/Feature Components/Codex Route Probe';
const codexAccountOrderStoryPath = 'frontend/src/features/codex/components/CodexAccountOrderComponents.stories.tsx';
const codexAccountOrderStorybookTitle = 'Design System/Feature Components/Codex Account Order';

export const designSystemComponentManifest = [
  {
    id: 'accounts-account-card',
    componentName: 'AccountCard',
    sourcePath: 'frontend/src/features/accounts/components/AccountCard.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '完整账号卡已通过 Account Cards story 收编，auth file 下载依赖已由 runtime wrapper 通过 downloadAuthFile prop 注入。',
    matchedPatterns: ['DebugPanel EntryCard'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'selection-selected', 'pending-delete', 'list-blocked'],
    mockDataSources: ['storybook AccountRecord/usage/rate-limit mock', 'storybook downloadAuthFile mock'],
  },
  {
    id: 'accounts-account-card-frame',
    componentName: 'AccountCardFrame',
    sourcePath: 'frontend/src/features/accounts/components/AccountCardFrame.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '可点击卡片外壳已通过 Account Cards story 收编，覆盖默认、选中和嵌套 action 边界。',
    matchedPatterns: ['DesignSystemStoryFrame'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['default', 'interactive-child', 'selected'],
    mockDataSources: ['storybook local mock'],
  },
  {
    id: 'accounts-account-card-skeleton',
    componentName: 'AccountCardSkeleton',
    sourcePath: 'frontend/src/features/accounts/components/AccountCardSkeleton.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号卡骨架屏已通过 Account Cards story 收编，覆盖卡片加载矩阵。',
    matchedPatterns: ['PageLoadingFallback'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['full', 'compact'],
    mockDataSources: ['storybook local mock'],
  },
  {
    id: 'accounts-account-detail-modal-frame',
    componentName: 'AccountDetailModalFrame',
    sourcePath: 'frontend/src/features/accounts/components/AccountDetailModalFrame.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号详情弹窗 shell 已通过 Account Modals story 收编，覆盖 header、滚动内容、错误条和 footer action。',
    matchedPatterns: ['DebugPanel details'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['default', 'long-content'],
    mockDataSources: ['storybook account modal content mock'],
  },
  {
    id: 'accounts-account-group-section',
    componentName: 'AccountGroupSection',
    sourcePath: 'frontend/src/features/accounts/components/AccountGroupSection.tsx',
    ownerFeature: 'accounts',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '业务 wrapper 继续组合 AccountCard 并注入 Wails auth file 下载函数；设计系统已收编无 Wails 的 AccountGroupSectionView。',
    matchedPatterns: ['DebugPanel grouped list'],
    suggestedDesignComponent: 'GroupedCardSection',
    revisitTrigger: 'AccountGroupSection 的 runtime-only downloadAuthFile 注入迁移到页面 controller 或纯 wrapper 边界后复查。',
  },
  {
    id: 'accounts-account-group-section-view',
    componentName: 'AccountGroupSectionView',
    sourcePath: 'frontend/src/features/accounts/components/AccountGroupSectionView.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号分组标题和响应式卡片网格已拆成无 Wails 的纯 view，并通过 Account Group Sections story 收编。',
    matchedPatterns: ['DebugPanel grouped list', 'AccountCardFrame'],
    storyPath: accountGroupSectionStoryPath,
    storybookTitle: accountGroupSectionStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['full-grid', 'compact-grid', 'list', 'empty'],
    mockDataSources: ['storybook account group and mock card renderer'],
  },
  {
    id: 'accounts-account-health-bar',
    componentName: 'AccountHealthBar',
    sourcePath: 'frontend/src/features/accounts/components/AccountHealthBar.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号健康条已通过 Account Cards story 收编，覆盖健康、混合失败和空闲块。',
    matchedPatterns: ['DebugPanel status card'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['healthy', 'warning', 'failed'],
    mockDataSources: ['storybook AccountUsageSummary mock'],
  },
  {
    id: 'accounts-account-proxy-route-section',
    componentName: 'AccountProxyRouteSection',
    sourcePath: 'frontend/src/features/accounts/components/AccountProxyRouteSection.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号代理出口选择区块已支持注入 proxy nodes，并通过 Account Proxy Route story 收编。',
    matchedPatterns: ['SegmentedControl', 'Combobox'],
    storyPath: accountProxyRouteStoryPath,
    storybookTitle: accountProxyRouteStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['inherit', 'direct', 'custom', 'detached-current-url', 'no-nodes', 'readonly'],
    mockDataSources: ['storybook injected proxy node mock'],
  },
  {
    id: 'accounts-account-rotation-modal',
    componentName: 'AccountRotationModal',
    sourcePath: 'frontend/src/features/accounts/components/AccountRotationModal.tsx',
    ownerFeature: 'accounts',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '依赖 useAccountRotation 加载/保存真实配置，不直接进入 Storybook；先拆纯 view。',
    matchedPatterns: ['ToggleSwitch', 'SegmentedControl'],
    suggestedDesignComponent: 'RotationSettingsDialog',
    revisitTrigger: '轮换 modal 拆出纯展示层后复查。',
  },
  {
    id: 'accounts-accounts-header',
    componentName: 'AccountsHeader',
    sourcePath: 'frontend/src/features/accounts/components/AccountsHeader.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号页头已通过 Accounts Header story 收编，覆盖默认、刷新中、菜单展开、未就绪和统一新增入口。',
    matchedPatterns: ['WorkspacePageHeader'],
    storyPath: accountsHeaderStoryPath,
    storybookTitle: accountsHeaderStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['default', 'loading', 'menu-open', 'not-ready', 'unified-compose'],
    mockDataSources: ['storybook accounts header refs and callbacks mock'],
  },
  {
    id: 'accounts-accounts-toolbar',
    componentName: 'AccountsToolbar',
    sourcePath: 'frontend/src/features/accounts/components/AccountsToolbar.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号工作台搜索、筛选、密度切换和批量选择工具栏已通过 Accounts Toolbar story 收编。',
    matchedPatterns: ['SegmentedControl'],
    storyPath: accountsToolbarStoryPath,
    storybookTitle: accountsToolbarStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['default', 'filters-open', 'empty-selection', 'bulk-selection'],
    mockDataSources: ['storybook account toolbar filters/search/display mode/selection mock'],
  },
  {
    id: 'accounts-list-workbench-view',
    componentName: 'AccountsListWorkbenchView',
    sourcePath: 'frontend/src/features/accounts/components/AccountsListWorkbenchView.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号列表整体已拆成无 Wails 的组合 view，并通过 Accounts List story 收编页头、工具栏、分组和账号卡片联动状态。',
    matchedPatterns: ['WorkspacePageHeader', 'SegmentedControl', 'AccountCardFrame'],
    storyPath: accountsListStoryPath,
    storybookTitle: accountsListStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['full-list', 'compact-list', 'selection-list', 'filtered-empty'],
    mockDataSources: ['storybook account groups, account cards, filters, display mode and selection mock'],
  },
  {
    id: 'accounts-api-key-compose-modal',
    componentName: 'ApiKeyComposeModal',
    sourcePath: 'frontend/src/features/accounts/components/ApiKeyComposeModal.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '新增 API key 弹窗已通过 Account Modals story 收编，覆盖空表单、已填 quota、模型拉取中和验证错误。',
    matchedPatterns: ['Combobox'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['empty', 'filled-quota', 'fetching-models', 'verify-error'],
    mockDataSources: ['storybook api key compose form mock', 'storybook probe callback mock'],
  },
  {
    id: 'accounts-api-key-detail-modal',
    componentName: 'ApiKeyDetailModal',
    sourcePath: 'frontend/src/features/accounts/components/ApiKeyDetailModal.tsx',
    ownerFeature: 'accounts',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '详情弹窗数据重且包含保存/验证/测试路径，先收编内部小组件和 modal shell。',
    matchedPatterns: ['Combobox', 'ToggleSwitch', 'DebugPanel details'],
    suggestedDesignComponent: 'CredentialDetailDialog',
    revisitTrigger: '详情页区块拆分或 mock handlers 稳定后复查。',
  },
  {
    id: 'accounts-attribution-card',
    componentName: 'AttributionCard',
    sourcePath: 'frontend/src/features/accounts/components/AttributionCard.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '归因卡已通过 Account Cards story 收编，覆盖健康、失败、紧凑和列表密度。',
    matchedPatterns: ['DebugPanel EntryCard'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['healthy', 'limited', 'failed', 'long-content'],
    mockDataSources: ['storybook AccountUsageSummary mock', 'storybook quota/billing/rate-limit mock'],
  },
  {
    id: 'accounts-card-sections',
    componentName: 'CardSections',
    sourcePath: 'frontend/src/features/accounts/components/CardSections.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号指标段已通过 Account Cards story 收编，覆盖 quota、billing、usage、rate-limit 和 evidence。',
    matchedPatterns: ['DebugPanel state matrix'],
    storyPath: accountCardStoryPath,
    storybookTitle: accountCardStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['quota', 'usage', 'billing', 'rate-limit', 'evidence'],
    mockDataSources: ['storybook quota/billing/usage/rate-limit mock'],
  },
  {
    id: 'accounts-codex-oauth-modal',
    componentName: 'CodexOAuthModal',
    sourcePath: 'frontend/src/features/accounts/components/CodexOAuthModal.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'OAuth URL 弹窗已通过 Account Modals story 收编，复制动作可用 mock handler 隔离，覆盖 ready、existing account 和 copy error。',
    matchedPatterns: ['DebugPanel empty/state'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'existing-copy-success', 'copy-error'],
    mockDataSources: ['storybook oauth url and copy state mock'],
  },
  {
    id: 'accounts-openai-compatible-compose-modal',
    componentName: 'OpenAICompatibleComposeModal',
    sourcePath: 'frontend/src/features/accounts/components/OpenAICompatibleComposeModal.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'OpenAI-compatible provider 新增表单已通过 OpenAI Compatible story 收编，覆盖空表单、preset selected 和校验错误。',
    matchedPatterns: ['ActionSelect'],
    storyPath: openAICompatibleStoryPath,
    storybookTitle: openAICompatibleStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['empty', 'preset-selected', 'validation-error'],
    mockDataSources: ['storybook openai-compatible compose form mock'],
  },
  {
    id: 'accounts-openai-compatible-detail-modal',
    componentName: 'OpenAICompatibleDetailModal',
    sourcePath: 'frontend/src/features/accounts/components/OpenAICompatibleDetailModal.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'OpenAI-compatible 完整详情弹窗已通过 RateLimitRulesAPI mock 隔离规则 CRUD，并在 OpenAI Compatible story 收编。',
    matchedPatterns: ['Combobox', 'ToggleSwitch'],
    storyPath: openAICompatibleStoryPath,
    storybookTitle: openAICompatibleStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['rate-limit-composed'],
    mockDataSources: ['storybook provider detail draft', 'storybook rate-limit status and CRUD API mock'],
  },
  {
    id: 'accounts-openai-compatible-detail-panel',
    componentName: 'OpenAICompatibleDetailPanel',
    sourcePath: 'frontend/src/features/accounts/components/OpenAICompatibleDetailPanel.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'OpenAI-compatible 详情主体已拆成无 Wails 展示层，并通过 OpenAI Compatible story 收编。',
    matchedPatterns: ['AccountDetailModalFrame', 'ActionSelect'],
    storyPath: openAICompatibleStoryPath,
    storybookTitle: openAICompatibleStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready-remote-models', 'validation-error', 'fetching-models'],
    mockDataSources: ['storybook provider draft, verify state, remote model state'],
  },
  {
    id: 'accounts-openai-compatible-provider-card',
    componentName: 'OpenAICompatibleProviderCard',
    sourcePath: 'frontend/src/features/accounts/components/OpenAICompatibleProviderCard.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'OpenAI-compatible provider 卡片已通过 OpenAI Compatible story 收编，覆盖验证成功、验证错误、禁用、pending 和 rate-limit blocked。',
    matchedPatterns: ['DebugPanel EntryCard'],
    storyPath: openAICompatibleStoryPath,
    storybookTitle: openAICompatibleStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'error', 'disabled', 'pending', 'rate-limit-blocked'],
    mockDataSources: ['storybook openai-compatible provider/verify/usage/rate-limit mock'],
  },
  {
    id: 'accounts-openai-compatible-workspace',
    componentName: 'OpenAICompatibleWorkspace',
    sourcePath: 'frontend/src/features/accounts/components/OpenAICompatibleWorkspace.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'OpenAI-compatible workspace 已通过 OpenAI Compatible story 收编，覆盖 loading、empty、grid 和 embedded 组合态。',
    matchedPatterns: ['WorkspacePageHeader', 'PageLoadingFallback'],
    storyPath: openAICompatibleStoryPath,
    storybookTitle: openAICompatibleStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['loading', 'empty', 'grid', 'embedded'],
    mockDataSources: ['storybook openai-compatible provider/verify/remote-models mock'],
  },
  {
    id: 'accounts-paste-auth-modal',
    componentName: 'PasteAuthModal',
    sourcePath: 'frontend/src/features/accounts/components/PasteAuthModal.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '粘贴导入弹窗已通过 Account Modals story 收编，覆盖空内容、已填内容和 JSON 错误状态。',
    matchedPatterns: ['DebugPanel details'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['empty', 'invalid-json', 'ready'],
    mockDataSources: ['storybook pasted auth payload mock'],
  },
  {
    id: 'accounts-rate-limit-rules-section',
    componentName: 'RateLimitRulesSection',
    sourcePath: 'frontend/src/features/accounts/components/RateLimitRulesSection.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '路由守卫规则编辑区块已通过可注入 RateLimitRulesAPI 隔离运行时 CRUD，并通过 Rate Limit Rules story 收编。',
    matchedPatterns: ['ToggleSwitch'],
    storyPath: rateLimitRulesStoryPath,
    storybookTitle: rateLimitRulesStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['active-rules', 'empty-rules', 'preview-fallback'],
    mockDataSources: ['storybook rate limit status and CRUD API mock'],
  },
  {
    id: 'accounts-unified-account-detail-modal',
    componentName: 'UnifiedAccountDetailModal',
    sourcePath: 'frontend/src/features/accounts/components/UnifiedAccountDetailModal.tsx',
    ownerFeature: 'accounts',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '直接调用 auth file 下载、模型读取和内容清洗，不直接进入设计系统。',
    matchedPatterns: ['Combobox', 'ToggleSwitch'],
    suggestedDesignComponent: 'AccountDetailWorkbench',
    revisitTrigger: '拆出无 Wails sections 后复查。',
  },
  {
    id: 'accounts-unified-compose-modal',
    componentName: 'UnifiedComposeModal',
    sourcePath: 'frontend/src/features/accounts/components/UnifiedComposeModal.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '统一新增账号两步弹窗已通过 Account Modals story 收编，覆盖 preset list、provider form step 和 validation error。',
    matchedPatterns: ['ActionSelect'],
    storyPath: accountModalStoryPath,
    storybookTitle: accountModalStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['preset-list', 'form-step', 'error'],
    mockDataSources: ['storybook unified compose form and vendor preset mock'],
  },
  {
    id: 'accounts-rotation-config-section',
    componentName: 'RotationConfigSection',
    sourcePath: 'frontend/src/features/accounts/components/account-rotation/RotationConfigSection.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号轮换 routing 配置表单已通过 Account Rotation story 收编，覆盖默认值和策略菜单展开态。',
    matchedPatterns: ['Combobox', 'ToggleSwitch'],
    storyPath: accountRotationStoryPath,
    storybookTitle: accountRotationStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['priority', 'random', 'disabled'],
    mockDataSources: ['storybook relay routing draft mock'],
  },
  {
    id: 'accounts-rotation-priority-item',
    componentName: 'RotationPriorityItem',
    sourcePath: 'frontend/src/features/accounts/components/account-rotation/RotationPriorityItem.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '账号轮换优先级项已通过 Account Rotation story 收编，覆盖普通、拖拽、pending 和 disabled 账号状态。',
    matchedPatterns: ['DebugPanel EntryCard'],
    storyPath: accountRotationStoryPath,
    storybookTitle: accountRotationStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['normal', 'dragging', 'disabled'],
    mockDataSources: ['storybook AccountRecord rotation mock'],
  },
  {
    id: 'accounts-usage-desk-chart',
    componentName: 'UsageDeskChart',
    sourcePath: 'frontend/src/features/accounts/components/usage-desk/UsageDeskChart.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Usage Desk 图表已通过 Usage Desk story 收编，覆盖双曲线、选中点、控件区和空态。',
    matchedPatterns: ['DebugPanel state matrix'],
    storyPath: usageDeskStoryPath,
    storybookTitle: usageDeskStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['observed', 'projected', 'empty'],
    mockDataSources: ['storybook usage chart point mock'],
  },
  {
    id: 'accounts-usage-desk-panels',
    componentName: 'UsageDeskPanels',
    sourcePath: 'frontend/src/features/accounts/components/usage-desk/UsageDeskPanels.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Usage Desk 信息面板和 session drilldown 已通过 Usage Desk story 收编，覆盖 totals、session rows 和空会话。',
    matchedPatterns: ['DebugPanel Empty', 'DebugPanel EntryCard'],
    storyPath: usageDeskStoryPath,
    storybookTitle: usageDeskStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['totals', 'session-drilldown', 'empty'],
    mockDataSources: ['storybook usage session mock'],
  },
  {
    id: 'accounts-usage-detail-table',
    componentName: 'UsageDetailTable',
    sourcePath: 'frontend/src/features/accounts/components/usage-desk/UsageDetailTable.tsx',
    ownerFeature: 'accounts',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Usage 明细表已通过 Usage Desk story 收编，覆盖 projected columns、选中行和空表。',
    matchedPatterns: ['DebugPanel log table'],
    storyPath: usageDeskStoryPath,
    storybookTitle: usageDeskStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['daily', 'selected', 'empty'],
    mockDataSources: ['storybook usage minute row mock'],
  },
  {
    id: 'codex-binary-summary-panel',
    componentName: 'CodexBinarySummaryPanel',
    sourcePath: 'frontend/src/features/codex-binary/components/CodexBinarySummaryPanel.tsx',
    ownerFeature: 'codex-binary',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '运行时版本摘要已通过 Codex Binary story 收编，覆盖托管 PATH、doctor error 和刷新动作。',
    matchedPatterns: ['WorkspacePageHeader'],
    storyPath: codexBinaryStoryPath,
    storybookTitle: codexBinaryStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['managed-path-disabled', 'managed-path-enabled', 'doctor-error'],
    mockDataSources: ['codexBinaryPreviewSnapshot'],
  },
  {
    id: 'codex-binary-version-cell',
    componentName: 'CodexBinaryVersionCell',
    sourcePath: 'frontend/src/features/codex-binary/components/CodexBinaryVersionCell.tsx',
    ownerFeature: 'codex-binary',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '可展开版本行已通过 Codex Binary story 收编，覆盖 active/download/expanded release notes。',
    matchedPatterns: ['ActionSelect', 'DebugPanel details'],
    storyPath: codexBinaryStoryPath,
    storybookTitle: codexBinaryStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['active', 'downloadable', 'expanded-notes'],
    mockDataSources: ['codexBinaryPreviewSnapshot', 'codexBinaryPreviewNotes'],
  },
  {
    id: 'codex-binary-version-list',
    componentName: 'CodexBinaryVersionList',
    sourcePath: 'frontend/src/features/codex-binary/components/CodexBinaryVersionList.tsx',
    ownerFeature: 'codex-binary',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '版本列表已通过 Codex Binary story 收编，覆盖筛选、展开行和空态。',
    matchedPatterns: ['SegmentedControl', 'DebugPanel list'],
    storyPath: codexBinaryStoryPath,
    storybookTitle: codexBinaryStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['stable-filter', 'all-filter', 'empty'],
    mockDataSources: ['codexBinaryPreviewSnapshot'],
  },
  {
    id: 'codex-account-detail-modal',
    componentName: 'CodexAccountDetailModal',
    sourcePath: 'frontend/src/features/codex/components/CodexAccountDetailModal.tsx',
    ownerFeature: 'codex',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex 账号详情弹窗已通过 Codex Account Order story 收编，覆盖映射编辑、空映射说明和保存中状态。',
    matchedPatterns: ['Combobox'],
    storyPath: codexAccountOrderStoryPath,
    storybookTitle: codexAccountOrderStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['mapped', 'empty-models', 'saving'],
    mockDataSources: ['storybook codex account row and model mapping mock'],
  },
  {
    id: 'codex-account-list-view',
    componentName: 'CodexAccountListView',
    sourcePath: 'frontend/src/features/codex/components/CodexAccountListView.tsx',
    ownerFeature: 'codex',
    status: 'deferred',
    tier: 'feature-component',
    decisionReason: '组合整个 account-list workspace，先收编下层 row/section/probe 组件。',
    matchedPatterns: ['WorkspacePageHeader', 'PageLoadingFallback'],
    suggestedDesignComponent: 'AccountListWorkspaceView',
    revisitTrigger: 'CodexAccountOrderRow/Section 和 ProbeCard 已有 stories 后复查。',
  },
  {
    id: 'codex-account-order-row',
    componentName: 'CodexAccountOrderRow',
    sourcePath: 'frontend/src/features/codex/components/CodexAccountOrderRow.tsx',
    ownerFeature: 'codex',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex 账号请求顺序行已通过 Codex Account Order story 收编，覆盖 full/compact/list、拖拽、probe hit、policy skipped、disabled 和 rate-limit blocked。',
    matchedPatterns: ['ToggleSwitch', 'DebugPanel EntryCard'],
    storyPath: codexAccountOrderStoryPath,
    storybookTitle: codexAccountOrderStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['full', 'compact', 'list', 'dragged', 'probe-hit', 'policy-skipped', 'disabled', 'rate-limit-blocked'],
    mockDataSources: ['storybook codex account row/policy/quota/usage/rate-limit mock'],
  },
  {
    id: 'codex-account-order-section',
    componentName: 'CodexAccountOrderSection',
    sourcePath: 'frontend/src/features/codex/components/CodexAccountOrderSection.tsx',
    ownerFeature: 'codex',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex 请求顺序列表容器已通过 Codex Account Order story 收编，覆盖密度、未保存、保存中、等待、加载和空列表。',
    matchedPatterns: ['SegmentedControl', 'DebugPanel list'],
    storyPath: codexAccountOrderStoryPath,
    storybookTitle: codexAccountOrderStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['compact', 'full-unsaved', 'list-saving', 'waiting', 'loading', 'empty'],
    mockDataSources: ['storybook codex account section rows/policy/quota/usage/rate-limit mock'],
  },
  {
    id: 'codex-route-probe-card',
    componentName: 'CodexRouteProbeCard',
    sourcePath: 'frontend/src/features/codex/components/CodexRouteProbeCard.tsx',
    ownerFeature: 'codex',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex 路由探测工作台已通过 Codex Route Probe story 收编，覆盖 idle、running、fallback 和空候选队列。',
    matchedPatterns: ['ToggleSwitch', 'Combobox', 'DebugPanel'],
    storyPath: codexRouteProbeStoryPath,
    storybookTitle: codexRouteProbeStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['idle', 'running', 'failed'],
    mockDataSources: ['storybook codex route probe row/log mock'],
  },
  {
    id: 'codex-model-combobox',
    componentName: 'ModelCombobox',
    sourcePath: 'frontend/src/features/codex/components/ModelCombobox.tsx',
    ownerFeature: 'codex',
    status: 'excluded',
    tier: 'feature-component',
    decisionReason: '只是 Combobox 的 Codex 模型薄包装，设计系统价值并入基础 Combobox，不单独收编。',
    matchedPatterns: ['Combobox'],
    suggestedDesignComponent: 'Combobox',
  },
  {
    id: 'debug-empty-state',
    componentName: 'DebugEmptyState',
    sourcePath: 'frontend/src/features/debug/components/DebugEmptyState.tsx',
    ownerFeature: 'debug',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '调试面板空状态已通过 Debug Panel story 收编。',
    matchedPatterns: ['DebugPanel Empty'],
    storyPath: debugPanelStoryPath,
    storybookTitle: debugPanelStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['empty'],
    mockDataSources: ['storybook local mock'],
  },
  {
    id: 'debug-entry-card',
    componentName: 'DebugEntryCard',
    sourcePath: 'frontend/src/features/debug/components/DebugEntryCard.tsx',
    ownerFeature: 'debug',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '调试日志卡片已通过 Debug Panel story 收编，覆盖成功、错误、折叠和选中状态。',
    matchedPatterns: ['DebugPanel EntryCard'],
    storyPath: debugPanelStoryPath,
    storybookTitle: debugPanelStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['success', 'error', 'collapsed', 'selected'],
    mockDataSources: ['storybook request/response mock'],
  },
  {
    id: 'debug-header',
    componentName: 'DebugHeader',
    sourcePath: 'frontend/src/features/debug/components/DebugHeader.tsx',
    ownerFeature: 'debug',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '调试面板工具栏已通过 Debug Panel story 收编。',
    matchedPatterns: ['DebugPanel toolbar'],
    storyPath: debugPanelStoryPath,
    storybookTitle: debugPanelStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['default', 'all-selected', 'copy-success'],
    mockDataSources: ['storybook local mock'],
  },
  {
    id: 'status-relay-editors',
    componentName: 'RelayEditors',
    sourcePath: 'frontend/src/features/status/components/RelayEditors.tsx',
    ownerFeature: 'status',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Relay key/provider/model editor modals 已通过 Status Relay Editors story 收编，覆盖创建、重命名、错误和模型输入状态。',
    matchedPatterns: ['DesignSystemStoryFrame'],
    storyPath: statusRelayEditorsStoryPath,
    storybookTitle: statusRelayEditorsStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['key-editor', 'provider-editor', 'model-editor'],
    mockDataSources: ['storybook relay editor state mock'],
  },
  {
    id: 'status-codex-features-section',
    componentName: 'StatusCodexFeaturesSection',
    sourcePath: 'frontend/src/features/status/components/StatusCodexFeaturesSection.tsx',
    ownerFeature: 'status',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Codex feature 配置列表已拆出并通过 Status Codex Features story 收编，覆盖 ready、dirty preview、saving、loading、empty 和 unsupported/readOnly 状态。',
    matchedPatterns: ['ToggleSwitch', 'SegmentedControl', 'DebugPanel list'],
    storyPath: statusCodexFeaturesStoryPath,
    storybookTitle: statusCodexFeaturesStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['ready', 'dirty-preview', 'saving', 'loading', 'empty', 'unsupported-readonly'],
    mockDataSources: ['storybook codex feature snapshot/rows/preview mock'],
  },
  {
    id: 'status-local-cli-apply-section',
    componentName: 'StatusApplyLocalSection',
    sourcePath: 'frontend/src/features/status/components/StatusPanels.tsx',
    ownerFeature: 'status',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: '本地 Codex / Claude Code 配置应用区块已通过 Status Local CLI Apply story 收编，覆盖 ready、blocked、preserve auth、applying 和 Claude ready。',
    matchedPatterns: ['SegmentedControl', 'ActionSelect', 'ToggleSwitch', 'DebugPanel details'],
    storyPath: statusLocalCliApplyStoryPath,
    storybookTitle: statusLocalCliApplyStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['codex-ready', 'codex-blocked', 'codex-preserve-auth', 'codex-applying', 'claude-ready'],
    mockDataSources: ['storybook relay key, endpoint, provider, model, auth state and diff mock'],
  },
  {
    id: 'status-snippet-panel',
    componentName: 'StatusSnippetPanel',
    sourcePath: 'frontend/src/features/status/components/StatusSnippetPanel.tsx',
    ownerFeature: 'status',
    status: 'admitted',
    tier: 'feature-component',
    decisionReason: 'Status 配置片段面板已拆成独立组件并通过 Status Snippet Panel story 收编，覆盖普通配置、diff、长行和 header action。',
    matchedPatterns: ['DebugPanel details'],
    storyPath: statusSnippetPanelStoryPath,
    storybookTitle: statusSnippetPanelStorybookTitle,
    catalogGroupId: 'feature-components',
    requiredStates: ['plain', 'diff', 'long-line', 'header-action'],
    mockDataSources: ['storybook local config snippet mock'],
  },
] as const satisfies readonly DesignSystemComponentManifestEntry[];

export function getAdmittedDesignSystemComponentManifest() {
  return designSystemComponentManifest.filter((entry) => entry.status === 'admitted');
}
