import type { ApiFormat } from '../../../types';

export interface VendorPreset {
  id: string;
  name: string;
  apiFormat: ApiFormat;
  supportedFormats: ApiFormat[];
  baseUrl: string;
  formatBaseUrls?: Partial<Record<ApiFormat, string>>;
  apiKeyPlaceholder: string;
  modelSuggestions: string[];
  category: 'official' | 'cn_official' | 'aggregator' | 'third_party' | 'cloud_provider';
  icon?: string;
  iconColor?: string;
  websiteUrl?: string;
  quotaCurlTemplate?: string;
  billingCurlTemplate?: string;
}

export function getFormatBaseUrl(preset: VendorPreset, format: ApiFormat): string {
  return preset.formatBaseUrls?.[format] ?? preset.baseUrl;
}

export const vendorPresets: VendorPreset[] = [
  // ==================== Official ====================
  {
    id: 'anthropic',
    name: 'Anthropic (Official)',
    apiFormat: 'anthropic',
    supportedFormats: ['anthropic'],
    baseUrl: 'https://api.anthropic.com',
    apiKeyPlaceholder: 'sk-ant-...',
    modelSuggestions: ['claude-sonnet-4-6', 'claude-opus-4-7', 'claude-haiku-4-5'],
    category: 'official',
    icon: 'anthropic',
    iconColor: '#D4915D',
  },
  // ==================== Chinese Vendors (Anthropic-compatible) ====================
  {
    id: 'deepseek',
    name: 'DeepSeek',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://api.deepseek.com/v1',
    quotaCurlTemplate: 'curl -sS "https://api.deepseek.com/user/balance" -H "Authorization: Bearer {{apiKey}}"',
    billingCurlTemplate: 'curl -sS "https://api.deepseek.com/user/balance" -H "Authorization: Bearer {{apiKey}}"',
    formatBaseUrls: {
      anthropic: 'https://api.deepseek.com/anthropic',
      openai_chat: 'https://api.deepseek.com/v1',
    },
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['deepseek-v4-pro', 'deepseek-v4-flash'],
    category: 'cn_official',
    icon: 'deepseek',
    iconColor: '#1E88E5',
    websiteUrl: 'https://platform.deepseek.com',
  },
  {
    id: 'zhipu',
    name: 'Zhipu GLM',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    formatBaseUrls: {
      anthropic: 'https://open.bigmodel.cn/api/anthropic',
      openai_chat: 'https://open.bigmodel.cn/api/paas/v4',
    },
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['glm-5', 'glm-4.7', 'glm-4.5-flash'],
    category: 'cn_official',
    icon: 'zhipu',
    iconColor: '#0F62FE',
    websiteUrl: 'https://open.bigmodel.cn',
  },
  {
    id: 'kimi',
    name: 'Kimi (Moonshot)',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://api.moonshot.cn/v1',
    formatBaseUrls: {
      anthropic: 'https://api.moonshot.cn/anthropic',
      openai_chat: 'https://api.moonshot.cn/v1',
    },
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['kimi-k2.6', 'kimi-k2.5'],
    category: 'cn_official',
    icon: 'kimi',
    iconColor: '#6366F1',
    websiteUrl: 'https://platform.moonshot.cn',
  },
  {
    id: 'stepfun',
    name: 'StepFun',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://api.stepfun.com/v1',
    formatBaseUrls: {
      openai_chat: 'https://api.stepfun.com/v1',
      anthropic: 'https://api.stepfun.com/step_plan',
    },
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['step-3.5-flash-2603'],
    category: 'cn_official',
    icon: 'stepfun',
    iconColor: '#16D6D2',
    websiteUrl: 'https://platform.stepfun.com',
  },
  {
    id: 'bailian',
    name: 'Bailian (DashScope)',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    formatBaseUrls: {
      openai_chat: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
      anthropic: 'https://dashscope.aliyuncs.com/apps/anthropic',
    },
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['qwen3.5-plus', 'qwen3.5-flash'],
    category: 'cn_official',
    icon: 'bailian',
    iconColor: '#624AFF',
    websiteUrl: 'https://bailian.console.aliyun.com',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://api.minimaxi.com/v1',
    formatBaseUrls: {
      openai_chat: 'https://api.minimaxi.com/v1',
      anthropic: 'https://api.minimaxi.com/anthropic',
    },
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['MiniMax-M2.7'],
    category: 'cn_official',
    icon: 'minimax',
    iconColor: '#FF6B6B',
    websiteUrl: 'https://platform.minimaxi.com',
  },
  {
    id: 'doubao',
    name: 'Doubao (Ark)',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    formatBaseUrls: {
      openai_chat: 'https://ark.cn-beijing.volces.com/api/v3',
      anthropic: 'https://ark.cn-beijing.volces.com/api/coding',
    },
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['doubao-seed-2-0-code-preview-latest'],
    category: 'cn_official',
    icon: 'doubao',
    iconColor: '#3370FF',
    websiteUrl: 'https://www.volcengine.com/product/doubao',
  },
  {
    id: 'longcat',
    name: 'Longcat',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://api.longcat.chat/anthropic',
    formatBaseUrls: {
      openai_chat: 'https://api.longcat.chat/anthropic',
      anthropic: 'https://api.longcat.chat/anthropic',
    },
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['LongCat-Flash-Chat'],
    category: 'cn_official',
    icon: 'longcat',
    iconColor: '#29E154',
    websiteUrl: 'https://longcat.chat/platform',
  },
  {
    id: 'xiaomimimo',
    name: 'Xiaomi MiMo',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://api.xiaomimimo.com/v1',
    formatBaseUrls: {
      openai_chat: 'https://api.xiaomimimo.com/v1',
      anthropic: 'https://api.xiaomimimo.com/anthropic',
    },
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['mimo-v2-pro'],
    category: 'cn_official',
    icon: 'xiaomimimo',
    iconColor: '#000000',
    websiteUrl: 'https://platform.xiaomimimo.com',
  },
  {
    id: 'bailing',
    name: 'BaiLing',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://api.tbox.cn/api/anthropic',
    formatBaseUrls: {
      openai_chat: 'https://api.tbox.cn/api/anthropic',
      anthropic: 'https://api.tbox.cn/api/anthropic',
    },
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['Ling-2.5-1T'],
    category: 'cn_official',
  },
  // ==================== Aggregators / Third-party (Anthropic-compatible) ====================
  {
    id: 'openrouter',
    name: 'OpenRouter',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://openrouter.ai/api',
    apiKeyPlaceholder: 'sk-or-...',
    modelSuggestions: ['anthropic/claude-sonnet-4.6', 'anthropic/claude-opus-4.7'],
    category: 'aggregator',
    icon: 'openrouter',
    iconColor: '#6566F1',
    websiteUrl: 'https://openrouter.ai',
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://api.siliconflow.cn',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['Pro/MiniMaxAI/MiniMax-M2.7'],
    category: 'aggregator',
    icon: 'siliconflow',
    iconColor: '#6E29F6',
    websiteUrl: 'https://siliconflow.cn',
  },
  {
    id: 'aihubmix',
    name: 'AiHubMix',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://aihubmix.com',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: [],
    category: 'aggregator',
    icon: 'aihubmix',
    iconColor: '#006FFB',
    websiteUrl: 'https://aihubmix.com',
  },
  {
    id: 'shengsuanyun',
    name: 'Shengsuanyun',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://router.shengsuanyun.com/api',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: [],
    category: 'aggregator',
    icon: 'shengsuanyun',
    websiteUrl: 'https://www.shengsuanyun.com',
  },
  {
    id: 'modelscope',
    name: 'ModelScope',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://api-inference.modelscope.cn',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['ZhipuAI/GLM-5'],
    category: 'aggregator',
    icon: 'modelscope',
    iconColor: '#624AFF',
    websiteUrl: 'https://modelscope.cn',
  },
  {
    id: 'compshare',
    name: 'Compshare',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://api.modelverse.cn',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: [],
    category: 'aggregator',
    icon: 'ucloud',
    iconColor: '#000000',
    websiteUrl: 'https://www.compshare.cn',
  },
  {
    id: 'therouter',
    name: 'TheRouter',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://api.therouter.ai',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['anthropic/claude-sonnet-4.6'],
    category: 'aggregator',
    websiteUrl: 'https://therouter.ai',
  },
  {
    id: 'novita',
    name: 'Novita AI',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'anthropic'],
    baseUrl: 'https://api.novita.ai/v1',
    formatBaseUrls: {
      openai_chat: 'https://api.novita.ai/v1',
      anthropic: 'https://api.novita.ai/anthropic',
    },
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['zai-org/glm-5'],
    category: 'aggregator',
    icon: 'novita',
    websiteUrl: 'https://novita.ai',
  },
  // ==================== OpenAI-Compatible Only ====================
  {
    id: 'openai',
    name: 'OpenAI',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat', 'openai_responses'],
    baseUrl: 'https://api.openai.com/v1',
    quotaCurlTemplate: 'curl -sS "https://api.openai.com/v1/organization/usage?limit=1" -H "Authorization: Bearer {{apiKey}}"',
    billingCurlTemplate: 'curl -sS "https://api.openai.com/v1/organization/costs?limit=30" -H "Authorization: Bearer {{apiKey}}"',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['gpt-5.4', 'gpt-5.2'],
    category: 'official',
    icon: 'openai',
    iconColor: '#000000',
    websiteUrl: 'https://platform.openai.com',
  },
  {
    id: 'groq',
    name: 'Groq',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat'],
    baseUrl: 'https://api.groq.com/openai/v1',
    apiKeyPlaceholder: 'gsk_...',
    modelSuggestions: ['llama3-70b-8192', 'llama3-8b-8192'],
    category: 'aggregator',
    icon: 'groq',
    websiteUrl: 'https://groq.com',
  },
  {
    id: 'together',
    name: 'Together',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat'],
    baseUrl: 'https://api.together.xyz/v1',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo'],
    category: 'aggregator',
    websiteUrl: 'https://together.ai',
  },
  {
    id: 'nvidia',
    name: 'Nvidia NIM',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat'],
    baseUrl: 'https://integrate.api.nvidia.com',
    apiKeyPlaceholder: 'nvapi-...',
    modelSuggestions: ['moonshotai/kimi-k2.5'],
    category: 'aggregator',
    icon: 'nvidia',
    iconColor: '#76B900',
    websiteUrl: 'https://build.nvidia.com',
  },
  // ==================== Non-Anthropic / Need Format Conversion ====================
  {
    id: 'gemini',
    name: 'Gemini Native',
    apiFormat: 'gemini_native',
    supportedFormats: ['gemini_native'],
    baseUrl: 'https://generativelanguage.googleapis.com',
    apiKeyPlaceholder: 'AIza...',
    modelSuggestions: ['gemini-3.1-pro', 'gemini-3-flash'],
    category: 'official',
    icon: 'gemini',
    iconColor: '#4285F4',
    websiteUrl: 'https://ai.google.dev',
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    apiFormat: 'openai_chat',
    supportedFormats: ['openai_chat'],
    baseUrl: 'https://api.githubcopilot.com',
    apiKeyPlaceholder: '(OAuth)',
    modelSuggestions: ['claude-sonnet-4.6'],
    category: 'third_party',
    icon: 'github',
    iconColor: '#000000',
    websiteUrl: 'https://github.com/features/copilot',
  },
  // ==================== Cloud Providers ====================
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock',
    apiFormat: 'anthropic',
    supportedFormats: ['anthropic'],
    baseUrl: 'https://bedrock-runtime.us-west-2.amazonaws.com',
    apiKeyPlaceholder: 'AKIA...',
    modelSuggestions: ['global.anthropic.claude-sonnet-4-6', 'global.anthropic.claude-opus-4-7'],
    category: 'cloud_provider',
    icon: 'aws',
    iconColor: '#FF9900',
    websiteUrl: 'https://aws.amazon.com/bedrock/',
  },
  // ==================== Partners ====================
  {
    id: 'packycode',
    name: 'PackyCode',
    apiFormat: 'anthropic',
    supportedFormats: ['anthropic'],
    baseUrl: 'https://www.packyapi.com',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: [],
    category: 'third_party',
    icon: 'packycode',
    websiteUrl: 'https://www.packyapi.com',
  },
  {
    id: 'cubence',
    name: 'Cubence',
    apiFormat: 'anthropic',
    supportedFormats: ['anthropic'],
    baseUrl: 'https://api.cubence.com',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: [],
    category: 'third_party',
    icon: 'cubence',
    websiteUrl: 'https://cubence.com',
  },
  {
    id: 'aigocode',
    name: 'AIGoCode',
    apiFormat: 'anthropic',
    supportedFormats: ['anthropic'],
    baseUrl: 'https://api.aigocode.com',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: [],
    category: 'third_party',
    icon: 'aigocode',
    iconColor: '#5B7FFF',
    websiteUrl: 'https://aigocode.com',
  },
  {
    id: 'dmxapi',
    name: 'DMXAPI',
    apiFormat: 'anthropic',
    supportedFormats: ['anthropic'],
    baseUrl: 'https://www.dmxapi.cn',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: [],
    category: 'aggregator',
    websiteUrl: 'https://www.dmxapi.cn',
  },
  {
    id: 'aicodemirror',
    name: 'AICodeMirror',
    apiFormat: 'anthropic',
    supportedFormats: ['anthropic'],
    baseUrl: 'https://api.aicodemirror.com/api/claudecode',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: [],
    category: 'third_party',
    icon: 'aicodemirror',
    websiteUrl: 'https://www.aicodemirror.com',
  },
  {
    id: 'pipellm',
    name: 'PIPELLM',
    apiFormat: 'anthropic',
    supportedFormats: ['anthropic'],
    baseUrl: 'https://cc-api.pipellm.ai',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['claude-opus-4-7', 'claude-sonnet-4-6'],
    category: 'aggregator',
    icon: 'pipellm',
    websiteUrl: 'https://code.pipellm.ai',
  },
  {
    id: 'katcoder',
    name: 'KAT-Coder',
    apiFormat: 'anthropic',
    supportedFormats: ['anthropic'],
    baseUrl: 'https://vanchin.streamlake.ai/api/gateway/v1/endpoints/EP_ID/claude-code-proxy',
    apiKeyPlaceholder: 'sk-...',
    modelSuggestions: ['KAT-Coder-Pro V1', 'KAT-Coder-Air V1'],
    category: 'cn_official',
    icon: 'catcoder',
    websiteUrl: 'https://console.streamlake.ai',
  },
];

const presetByID = new Map(vendorPresets.map((p) => [p.id, p]));

export function getVendorPreset(id: string): VendorPreset | undefined {
  return presetByID.get(id);
}

export function getVendorPresets(): readonly VendorPreset[] {
  return vendorPresets;
}
