import type { CodexBinarySnapshot, CodexBinaryVersionNotes } from './model';

export const codexBinaryPreviewSnapshot: CodexBinarySnapshot = {
  manifestPath: '~/.config/gettokens-dev/codex/manifest.json',
  managedBinPath: '~/.config/gettokens-dev/codex/bin/codex',
  managedConfig: {
    binDir: '~/.config/gettokens-dev/codex/bin',
    binPath: '~/.config/gettokens-dev/codex/bin/codex',
    enableCommand: 'export PATH="$HOME/.config/gettokens-dev/codex/bin:$PATH"',
    profilePath: '~/.zprofile',
    profileKind: 'zsh',
    isPathConfigured: false,
    resolvedCodexPath: '/opt/homebrew/bin/codex',
    isResolvedToManaged: false,
  },
  selectedVersionID: '0.118.0-a1b2c3d4',
  currentVersion: {
    id: '0.118.0-a1b2c3d4',
    displayName: 'Codex 0.118.0',
    detectedVersion: '0.118.0',
    releaseTag: 'rust-v0.118.0',
    sourceID: 'openai-codex-github',
    sourceType: 'download',
    installedAt: '2026-05-10T18:20:00Z',
    lastActivatedAt: '2026-05-11T09:12:00Z',
    isSelected: true,
    existsOnDisk: true,
    binaryPath: '~/.config/gettokens-dev/codex/versions/0.118.0-a1b2c3d4/codex',
  },
  versions: [
    {
      id: '0.118.0-a1b2c3d4',
      displayName: 'Codex 0.118.0',
      detectedVersion: '0.118.0',
      releaseTag: 'rust-v0.118.0',
      sourceID: 'openai-codex-github',
      sourceType: 'download',
      installedAt: '2026-05-10T18:20:00Z',
      lastActivatedAt: '2026-05-11T09:12:00Z',
      isSelected: true,
      existsOnDisk: true,
    },
    {
      id: '0.116.1-c3d4e5f6',
      displayName: 'Codex 0.116.1',
      detectedVersion: '0.116.1',
      releaseTag: 'rust-v0.116.1',
      sourceID: 'openai-codex-github',
      sourceType: 'download',
      installedAt: '2026-05-03T14:45:00Z',
      isSelected: false,
      existsOnDisk: true,
    },
  ],
  remoteVersions: [
    {
      sourceID: 'openai-codex-github',
      version: '0.120.0',
      tag: 'rust-v0.120.0',
      title: 'rust-v0.120.0',
      downloadURL: 'https://github.com/openai/codex/releases/download/rust-v0.120.0/codex-aarch64-apple-darwin.tar.gz',
      htmlURL: 'https://github.com/openai/codex/releases/tag/rust-v0.120.0',
      assetName: 'codex-aarch64-apple-darwin.tar.gz',
      assetSize: 18400000,
      publishedAt: '2026-05-12T02:10:00Z',
      isPrerelease: false,
      isInstalled: false,
    },
    {
      sourceID: 'openai-codex-github',
      version: '0.119.2',
      tag: 'rust-v0.119.2',
      title: 'rust-v0.119.2',
      downloadURL: 'https://github.com/openai/codex/releases/download/rust-v0.119.2/codex-aarch64-apple-darwin.tar.gz',
      publishedAt: '2026-05-11T06:30:00Z',
      isPrerelease: false,
      isInstalled: false,
    },
  ],
  downloadTasks: [
    {
      id: 'dl-preview-120',
      sourceID: 'openai-codex-github',
      tag: 'rust-v0.120.0',
      version: '0.120.0',
      status: 'downloading',
      phase: 'download',
      bytesDone: 9200000,
      bytesTotal: 18400000,
      installAfterDownload: true,
      activateAfterInstall: true,
      updatedAt: '2026-05-12T08:00:00Z',
    },
  ],
  doctor: {
    severity: 'ok',
    message: '托管版本可用',
  },
};

export const codexBinaryPreviewNotes: CodexBinaryVersionNotes = {
  sourceID: 'openai-codex-github',
  tag: 'rust-v0.120.0',
  version: '0.120.0',
  title: 'rust-v0.120.0',
  htmlURL: 'https://github.com/openai/codex/releases/tag/rust-v0.120.0',
  publishedAt: '2026-05-12T02:10:00Z',
  bodyMarkdown: '### 变更记录\n\n- 优化启动速度和日志输出。\n- 修复 macOS arm64 包内二进制权限。\n- 改进 `codex --version` 输出兼容性。',
  bodyPlainText: '优化启动速度和日志输出；修复 macOS arm64 包内二进制权限。',
  source: 'cache',
  truncated: false,
};
