import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('ProxyPoolFeature uses the current workspace table layout', async () => {
  const source = await readFile(new URL('./ProxyPoolFeature.tsx', import.meta.url), 'utf8');
  const styleSource = await readFile(new URL('../../style.css', import.meta.url), 'utf8');
  const headerSource = await readFile(new URL('../../components/ui/WorkspacePageHeader.tsx', import.meta.url), 'utf8');

  assert.match(source, /data-proxy-pool-summary="true"/);
  assert.match(source, /data-proxy-pool-toolbar="true"/);
  assert.match(source, /data-proxy-pool-table="true"/);
  assert.match(source, /data-proxy-pool-modal="compose"/);
  assert.match(source, /data-proxy-pool-modal="import"/);
  assert.match(source, /data-proxy-pool-modal="subscription"/);
  assert.match(source, /data-proxy-pool-modal="subscription-manager"/);
  assert.match(headerSource, /meta\?: ReactNode;/);
  assert.match(headerSource, /\{meta \? <div className=\{`mt-2 min-w-0 \$\{metaClassName\}`\.trim\(\)\}>\{meta\}<\/div> : null\}/);
  assert.match(source, /import \{ AutoComplete, Button, Checkbox, Input, Select, Upload \} from 'antd'/);
  assert.match(source, /import \{ Download, FileInput, ListChecks, MoreVertical, Pencil, Play, Plus, RefreshCw, Trash2, Upload as UploadIcon, X \} from 'lucide-react'/);
  assert.match(source, /const summaryText = `显示 \$\{filteredNodes\.length\} \/ \$\{summary\.totalCount\} · 可用 \$\{summary\.availableCount\}/);
  assert.match(source, /meta=\{\s*<span[\s\S]*data-proxy-pool-summary="true"[\s\S]*\{summaryText\}/);
  assert.match(source, /actionsClassName="gap-2"/);
  assert.match(source, /title=\{summaryText\}/);
  assert.match(source, /className="block truncate font-mono text-\[length:var\(--gt-font-size-lg\)\]" title=\{url\}/);
  assert.match(source, /<AutoComplete[\s\S]*options=\{probeTargetOptions\}/);
  assert.match(source, /onSelect=\{\(url\) => \{[\s\S]*rememberProxyProbeTargetURL\(current, url\)/);
  assert.match(source, /data-proxy-pool-toolbar="true"[\s\S]*className="contents"/);
  assert.match(source, /lg:grid-cols-\[minmax\(0,1fr\)_minmax\(26rem,36rem\)\]/);
  assert.match(source, /<SearchInput[\s\S]*className="rounded-md"/);
  assert.match(source, /className="grid min-w-0 items-center gap-2 sm:grid-cols-\[max-content_minmax\(0,1fr\)\]"/);
  assert.match(source, /className="text-left text-sm font-normal text-\[var\(--gt-ink-muted\)\]">测速网址/);
  assert.match(source, /className="grid min-w-0 grid-cols-\[minmax\(0,1fr\)_auto\] items-center gap-2"/);
  assert.match(source, /<Button[\s\S]*aria-label=\{probingIDs\.length > 0 \? '测速中' : '执行测速'\}[\s\S]*icon=\{<Play className="h-3\.5 w-3\.5" fill="currentColor" strokeWidth=\{2\.4\} \/>\}[\s\S]*loading=\{probingIDs\.length > 0\}[\s\S]*disabled=\{filteredNodes\.length === 0\}[\s\S]*className="proxy-pool-probe-target-button"[\s\S]*onClick=\{handleBatchRetest\}/);
  assert.match(source, /<Button[\s\S]*type="primary"[\s\S]*aria-label="新增代理"[\s\S]*icon=\{<Plus className="h-5 w-5" strokeWidth=\{2\.5\} \/>\}/);
  assert.match(source, /<Button[\s\S]*aria-label="更多操作"[\s\S]*icon=\{<MoreVertical className="h-5 w-5" strokeWidth=\{2\.5\} \/>\}/);
  assert.match(source, /className="overflow-hidden rounded-md border border-\[var\(--gt-border-subtle\)\] bg-\[var\(--gt-surface-canvas\)\]"/);
  assert.match(source, /<Button[\s\S]*aria-label=\{probing \? '测速中' : '测速'\}[\s\S]*disabled=\{probing\}[\s\S]*className="flex h-8 w-8 items-center justify-center rounded disabled:cursor-not-allowed disabled:opacity-50"/);
  assert.match(source, /<Button[\s\S]*aria-label="更多操作"[\s\S]*icon=\{<MoreVertical className="h-4 w-4" strokeWidth=\{2\.4\} \/>\}[\s\S]*className="flex h-8 w-8 items-center justify-center rounded"/);
  assert.doesNotMatch(source, /active:scale/);
  assert.match(source, /const proxyPoolModalPanelClass = 'flex w-full flex-col overflow-hidden rounded-md border border-\[var\(--gt-border-subtle\)\] bg-\[var\(--gt-surface-canvas\)\] shadow-sm'/);
  assert.match(source, /<Input[\s\S]*placeholder="例如：127\.0\.0\.1"/);
  assert.match(source, /<Input\.TextArea/);
  assert.match(source, /<Button type="primary" size="small" onClick=\{onSubmit\}/);
  assert.match(source, /<h3 className="text-sm font-semibold text-\[var\(--gt-ink-primary\)\]">导入代理订阅<\/h3>/);
  assert.match(source, /<section key=\{source\.id\} className="rounded-md border border-\[var\(--gt-border-subtle\)\] bg-\[var\(--gt-surface-canvas\)\]">/);
  assert.match(styleSource, /\.proxy-pool-probe-target-autocomplete\.ant-select \{[\s\S]*height: 2\.75rem;/);
  assert.match(styleSource, /\.proxy-pool-probe-target-autocomplete\.ant-select \{[\s\S]*font-size: var\(--gt-font-size-lg\);/);
  assert.match(styleSource, /\.proxy-pool-probe-target-autocomplete \.ant-select-selector \{[\s\S]*background: var\(--gt-surface-canvas\) !important;/);
  assert.match(styleSource, /\.proxy-pool-probe-target-autocomplete \.ant-select-selection-search-input,[\s\S]*font-size: var\(--gt-font-size-lg\) !important;[\s\S]*line-height: 1\.25rem !important;/);
  assert.match(styleSource, /\.proxy-pool-probe-target-button\.ant-btn \{[\s\S]*height: 2\.75rem;[\s\S]*width: 2\.75rem;[\s\S]*padding: 0;[\s\S]*font-size: var\(--gt-font-size-lg\);/);
  assert.doesNotMatch(source, /<Button[\s\S]{0,500}\n\s*执行\n\s*<\/Button>/);
  assert.doesNotMatch(source, /shadow-\[6px_6px_0_var\(--gt-shadow-panel\)\]/);
  assert.doesNotMatch(source, /shadow-\[/);
  assert.doesNotMatch(source, /shadow-hard/);
  assert.doesNotMatch(source, /btn-swiss/);
  assert.doesNotMatch(source, /input-swiss/);
  assert.doesNotMatch(source, /border-2 border-\[var\(--gt-border-strong\)\]/);
  assert.doesNotMatch(source, /font-(?:medium|bold|extrabold|black)/);
  assert.doesNotMatch(source, /uppercase/);
  assert.doesNotMatch(source, /--text-on-accent|--bg-(main|surface|subtle|warning)/);
  assert.doesNotMatch(source, /subtitle=\{`网络代理池 \/ 本地维护/);
  assert.doesNotMatch(source, /subtitle="本地代理池 \/ 节点维护 \/ 可用性检测"/);
  assert.doesNotMatch(source, /<datalist id="proxy-probe-target-history">/);
  assert.doesNotMatch(source, /<span className="text-\[length:var\(--gt-font-size-xs\)\] font-normal text-\[var\(--gt-ink-muted\)\]">历史<\/span>/);
  assert.doesNotMatch(source, /<span>新增代理<\/span>/);
  assert.doesNotMatch(source, /<span>更多<\/span>/);
  assert.doesNotMatch(source, /<span>\{probing \? '测速中' : '测速'\}<\/span>/);
  assert.doesNotMatch(source, /<section[\s\S]{0,120}data-proxy-pool-summary="true"/);
  assert.doesNotMatch(source, /summaryItems\.map/);
  assert.doesNotMatch(source, /data-proxy-pool-toolbar="true"[\s\S]{0,120}className="rounded-md border/);
  assert.doesNotMatch(source, /data-proxy-pool-table="true" className="border-2 border-\[var\(--gt-border-strong\)\] bg-\[var\(--bg-(main|surface)\)\]"/);
  assert.doesNotMatch(source, /--gt-surface-page/);
});
