import type { DoctorSnapshot } from './doctorWorkbench';

export function getDoctorWorkbenchPreviewSnapshot(): DoctorSnapshot {
  return {
    generatedAtUnixMs: 1781596800000,
    source: 'preview',
    sidecarReady: true,
    status: 'warning',
    checks: [
      {
        id: 'applied-not-routeable',
        kind: 'local-apply-mismatch',
        title: 'Applied but not routeable',
        status: 'critical',
        reason: 'Local Codex config was applied, but sidecar route guard still blocks the selected account.',
        repairability: 'guided',
        authority: 'sidecar',
        confidence: 'high',
        lastCheckedAtUnixMs: 1781596740000,
        evidence: [
          {
            kind: 'account',
            label: 'codex-api-key:stable-001',
            summary: 'Account exists and local apply references it.',
            refID: 'codex-api-key:stable-001',
            source: 'wails-aggregate',
          },
          {
            kind: 'route_decision',
            label: 'route decision rd_preview_001',
            summary: 'Dropped by stale guard after local apply.',
            refID: 'rd_preview_001',
            source: 'sidecar',
          },
        ],
        navigation: [
          { kind: 'account_detail', label: 'Open account detail', hash: '#frame=accounts&detail=codex-api-key%3Astable-001' },
          { kind: 'route_decisions', label: 'Open route decisions', hash: '#frame=codex&workspace=account-list' },
        ],
      },
      {
        id: 'catalog-visible-no-backing',
        kind: 'model-registry-empty',
        title: 'Catalog visible but no provider backing',
        status: 'warning',
        reason: 'Model catalog contains gpt-5.4-mini, but no enabled provider currently backs it.',
        repairability: 'manual',
        authority: 'sidecar',
        confidence: 'medium',
        lastCheckedAtUnixMs: 1781596700000,
        evidence: [
          {
            kind: 'model',
            label: 'gpt-5.4-mini',
            summary: 'Visible in catalog without a provider candidate.',
            refID: 'gpt-5.4-mini',
            source: 'sidecar',
          },
        ],
        navigation: [{ kind: 'model_catalog', label: 'Open model catalog', hash: '#codex/vendor-status' }],
      },
      {
        id: 'stale-route-guard',
        kind: 'route-guard-stale-block',
        title: 'Stale route guard',
        status: 'warning',
        reason: 'Route guard block is older than the latest successful provider probe.',
        repairability: 'guided',
        authority: 'sidecar',
        confidence: 'high',
        lastCheckedAtUnixMs: 1781596680000,
        evidence: [
          {
            kind: 'route_decision',
            label: 'guard block codex-api-key:gray-canary',
            summary: 'Blocked for 1h requests, but provider probe recovered later.',
            refID: 'guard_preview_001',
            source: 'sidecar',
          },
        ],
        navigation: [{ kind: 'route_decisions', label: 'Open route decisions', hash: '#frame=codex&workspace=account-list' }],
      },
      {
        id: 'route_guard_dropped_reasons',
        kind: 'route-guard-stale-block',
        title: 'Structured route evidence',
        status: 'warning',
        reason: 'Shared digest semantics group dropped reasons by stable route identity; partial identity stays fallback-only.',
        repairability: 'read_only',
        authority: 'sidecar',
        confidence: 'high',
        lastCheckedAtUnixMs: 1781596660000,
        evidence: [
          {
            kind: 'route_dropped_reason',
            label: 'account=acct_wrong_preview auth=auth_wrong_preview',
            summary: 'scope=account reason=conflicting preview text routeBlocking=false',
            refID: 'rd_preview_nested_dropped_reason',
            source: 'preview-text-conflict',
            droppedReason: {
              accountKey: 'acct_route_001',
              accountId: 'acct_route_001',
              authId: 'auth_route_001',
              model: 'gpt-5',
              source: 'upstream-error',
              scope: 'model',
              reason: 'nested preview droppedReason survives browser fixture',
              routeBlocking: true,
            },
          },
          {
            kind: 'route_dropped_reason',
            label: 'auth=auth_route_001 account=acct_route_001',
            summary: 'routeBlocking=true reason=temporary upstream timeout after stale guard scope=model',
            refID: 'model=gpt-5',
            source: 'upstream-error',
          },
          {
            kind: 'route_dropped_reason',
            label: 'account=acct_partial_route auth=auth_partial_route',
            summary: 'reason=partial identity fallback kept as plain evidence',
            refID: 'rd_partial_route_001',
            source: 'upstream-error',
            routeEvidence: {
              accountKey: 'acct_partial_route',
              authId: 'auth_partial_route',
              reason: 'partial identity fallback kept as plain evidence',
              routeBlocking: true,
            },
          },
        ],
        navigation: [{ kind: 'route_decisions', label: 'Open route decisions', hash: '#frame=codex&workspace=account-list' }],
      },
      {
        id: 'account-store-startup-reconcile',
        kind: 'account-store-startup-reconcile',
        title: 'Account store startup reconcile',
        status: 'ok',
        reason: 'Account SQLite opened without recovery events.',
        repairability: 'none',
        authority: 'wails',
        confidence: 'high',
        lastCheckedAtUnixMs: 1781596600000,
        evidence: [
          {
            kind: 'sidecar_status',
            label: 'accounts-v1.sqlite',
            summary: 'Open with no recovery events.',
            refID: 'accounts-v1.sqlite',
            source: 'wails-aggregate',
          },
        ],
        navigation: [{ kind: 'status', label: 'Open status', hash: '#frame=status' }],
      },
    ],
  };
}
