// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {sidecar} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckUpdate():Promise<updater.ReleaseInfo>;

export function GetSidecarStatus():Promise<sidecar.Status>;

export function GetVersion():Promise<string>;
