// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeCodexSessions(arg1) {
  return window['go']['main']['App']['AnalyzeCodexSessions'](arg1);
}

export function ApplyClaudeCodeAPIKeyConfigToLocal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyClaudeCodeAPIKeyConfigToLocal'](arg1, arg2, arg3);
}

export function ApplyDeepLinkImport(arg1) {
  return window['go']['main']['App']['ApplyDeepLinkImport'](arg1);
}

export function ApplyGetTokensExtensionCodexConfigTransaction(arg1) {
  return window['go']['main']['App']['ApplyGetTokensExtensionCodexConfigTransaction'](arg1);
}

export function ApplyRelayServiceConfigToLocal(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ApplyRelayServiceConfigToLocal'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ApplyRelayServiceConfigToLocalV2(arg1) {
  return window['go']['main']['App']['ApplyRelayServiceConfigToLocalV2'](arg1);
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CanApplyUpdate() {
  return window['go']['main']['App']['CanApplyUpdate']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearCodexLiveSessions() {
  return window['go']['main']['App']['ClearCodexLiveSessions']();
}

export function CommitAccountMigration() {
  return window['go']['main']['App']['CommitAccountMigration']();
}

export function ConsumeOpenAIQuotaResetCredit(arg1) {
  return window['go']['main']['App']['ConsumeOpenAIQuotaResetCredit'](arg1);
}

export function ConsumePendingDeepLinks() {
  return window['go']['main']['App']['ConsumePendingDeepLinks']();
}

export function CreateCodexAPIKey(arg1) {
  return window['go']['main']['App']['CreateCodexAPIKey'](arg1);
}

export function CreateOpenAICompatibleProvider(arg1) {
  return window['go']['main']['App']['CreateOpenAICompatibleProvider'](arg1);
}

export function CreateProjectCandidatePoolRule(arg1) {
  return window['go']['main']['App']['CreateProjectCandidatePoolRule'](arg1);
}

export function CreateRateLimitRule(arg1) {
  return window['go']['main']['App']['CreateRateLimitRule'](arg1);
}

export function DeleteAccountsBatch(arg1) {
  return window['go']['main']['App']['DeleteAccountsBatch'](arg1);
}

export function DeleteAuthFiles(arg1) {
  return window['go']['main']['App']['DeleteAuthFiles'](arg1);
}

export function DeleteClaudeCodeSubagent(arg1) {
  return window['go']['main']['App']['DeleteClaudeCodeSubagent'](arg1);
}

export function DeleteCodexAPIKey(arg1) {
  return window['go']['main']['App']['DeleteCodexAPIKey'](arg1);
}

export function DeleteCodexBinaryVersion(arg1) {
  return window['go']['main']['App']['DeleteCodexBinaryVersion'](arg1);
}

export function DeleteLegacyAccountSources() {
  return window['go']['main']['App']['DeleteLegacyAccountSources']();
}

export function DeleteOpenAICompatibleProvider(arg1) {
  return window['go']['main']['App']['DeleteOpenAICompatibleProvider'](arg1);
}

export function DeleteProjectCandidatePoolRule(arg1) {
  return window['go']['main']['App']['DeleteProjectCandidatePoolRule'](arg1);
}

export function DeleteRateLimitRule(arg1) {
  return window['go']['main']['App']['DeleteRateLimitRule'](arg1);
}

export function DisableGetTokensCodexModelCatalogProjection() {
  return window['go']['main']['App']['DisableGetTokensCodexModelCatalogProjection']();
}

export function DownloadAuthFile(arg1) {
  return window['go']['main']['App']['DownloadAuthFile'](arg1);
}

export function DownloadCodexBinary(arg1) {
  return window['go']['main']['App']['DownloadCodexBinary'](arg1);
}

export function EnableCodexBinaryManagedPath() {
  return window['go']['main']['App']['EnableCodexBinaryManagedPath']();
}

export function EnableGetTokensCodexModelCatalogProjection(arg1) {
  return window['go']['main']['App']['EnableGetTokensCodexModelCatalogProjection'](arg1);
}

export function ExplainChannelRouting(arg1) {
  return window['go']['main']['App']['ExplainChannelRouting'](arg1);
}

export function FetchOpenAICompatibleProviderModels(arg1) {
  return window['go']['main']['App']['FetchOpenAICompatibleProviderModels'](arg1);
}

export function FetchProxySubscription(arg1) {
  return window['go']['main']['App']['FetchProxySubscription'](arg1);
}

export function FetchVendorStatusRSS(arg1) {
  return window['go']['main']['App']['FetchVendorStatusRSS'](arg1);
}

export function FinalizeCodexOAuth(arg1) {
  return window['go']['main']['App']['FinalizeCodexOAuth'](arg1);
}

export function GetAccountMigrationPreview() {
  return window['go']['main']['App']['GetAccountMigrationPreview']();
}

export function GetAccountStoreDiagnostics() {
  return window['go']['main']['App']['GetAccountStoreDiagnostics']();
}

export function GetAllQuotaStatuses() {
  return window['go']['main']['App']['GetAllQuotaStatuses']();
}

export function GetAllRateLimitStatuses() {
  return window['go']['main']['App']['GetAllRateLimitStatuses']();
}

export function GetAppRuntimeSettings() {
  return window['go']['main']['App']['GetAppRuntimeSettings']();
}

export function GetAuthFileModels(arg1) {
  return window['go']['main']['App']['GetAuthFileModels'](arg1);
}

export function GetChannelRoutingConfig(arg1) {
  return window['go']['main']['App']['GetChannelRoutingConfig'](arg1);
}

export function GetClaudeCodeExtensionsSnapshot() {
  return window['go']['main']['App']['GetClaudeCodeExtensionsSnapshot']();
}

export function GetClaudeCodeMemoryFilesSnapshot() {
  return window['go']['main']['App']['GetClaudeCodeMemoryFilesSnapshot']();
}

export function GetClaudeCodeSessionDetail(arg1) {
  return window['go']['main']['App']['GetClaudeCodeSessionDetail'](arg1);
}

export function GetClaudeCodeSessionManagementSnapshot() {
  return window['go']['main']['App']['GetClaudeCodeSessionManagementSnapshot']();
}

export function GetClaudeCodeSessionMessagePage(arg1, arg2) {
  return window['go']['main']['App']['GetClaudeCodeSessionMessagePage'](arg1, arg2);
}

export function GetClaudeCodeSessionMessageRawJSON(arg1, arg2) {
  return window['go']['main']['App']['GetClaudeCodeSessionMessageRawJSON'](arg1, arg2);
}

export function GetClaudeCodeSettingsSnapshot() {
  return window['go']['main']['App']['GetClaudeCodeSettingsSnapshot']();
}

export function GetClaudeCodeSubagentsSnapshot() {
  return window['go']['main']['App']['GetClaudeCodeSubagentsSnapshot']();
}

export function GetClaudeLocalUsage() {
  return window['go']['main']['App']['GetClaudeLocalUsage']();
}

export function GetCodexBinaryDoctor() {
  return window['go']['main']['App']['GetCodexBinaryDoctor']();
}

export function GetCodexBinarySnapshot() {
  return window['go']['main']['App']['GetCodexBinarySnapshot']();
}

export function GetCodexBinaryVersionNotes(arg1) {
  return window['go']['main']['App']['GetCodexBinaryVersionNotes'](arg1);
}

export function GetCodexConfigToml() {
  return window['go']['main']['App']['GetCodexConfigToml']();
}

export function GetCodexFeatureConfig() {
  return window['go']['main']['App']['GetCodexFeatureConfig']();
}

export function GetCodexLiveSessionHistory(arg1) {
  return window['go']['main']['App']['GetCodexLiveSessionHistory'](arg1);
}

export function GetCodexLiveSessionsSnapshot() {
  return window['go']['main']['App']['GetCodexLiveSessionsSnapshot']();
}

export function GetCodexLocalUsage() {
  return window['go']['main']['App']['GetCodexLocalUsage']();
}

export function GetCodexMcpServers() {
  return window['go']['main']['App']['GetCodexMcpServers']();
}

export function GetCodexModelCatalogDiagnostics() {
  return window['go']['main']['App']['GetCodexModelCatalogDiagnostics']();
}

export function GetCodexQuota(arg1) {
  return window['go']['main']['App']['GetCodexQuota'](arg1);
}

export function GetCodexQuotaBatchRefreshJob(arg1) {
  return window['go']['main']['App']['GetCodexQuotaBatchRefreshJob'](arg1);
}

export function GetCodexSessionDetail(arg1) {
  return window['go']['main']['App']['GetCodexSessionDetail'](arg1);
}

export function GetCodexSessionManagementSnapshot() {
  return window['go']['main']['App']['GetCodexSessionManagementSnapshot']();
}

export function GetCodexSessionMessagePage(arg1, arg2) {
  return window['go']['main']['App']['GetCodexSessionMessagePage'](arg1, arg2);
}

export function GetCodexSessionMessageRawJSON(arg1, arg2) {
  return window['go']['main']['App']['GetCodexSessionMessageRawJSON'](arg1, arg2);
}

export function GetCodexSkillFilePreview(arg1) {
  return window['go']['main']['App']['GetCodexSkillFilePreview'](arg1);
}

export function GetCodexSkillsSnapshot() {
  return window['go']['main']['App']['GetCodexSkillsSnapshot']();
}

export function GetDoctorSnapshot(arg1) {
  return window['go']['main']['App']['GetDoctorSnapshot'](arg1);
}

export function GetGetTokensExtensionRegistrySnapshot(arg1) {
  return window['go']['main']['App']['GetGetTokensExtensionRegistrySnapshot'](arg1);
}

export function GetLocalCodexAuthState() {
  return window['go']['main']['App']['GetLocalCodexAuthState']();
}

export function GetLocalCodexModelProviderStateView() {
  return window['go']['main']['App']['GetLocalCodexModelProviderStateView']();
}

export function GetLocalProjectedUsageSettings() {
  return window['go']['main']['App']['GetLocalProjectedUsageSettings']();
}

export function GetOAuthStatus(arg1) {
  return window['go']['main']['App']['GetOAuthStatus'](arg1);
}

export function GetOpenAIQuotaResetCredit(arg1) {
  return window['go']['main']['App']['GetOpenAIQuotaResetCredit'](arg1);
}

export function GetQuotaStatus(arg1) {
  return window['go']['main']['App']['GetQuotaStatus'](arg1);
}

export function GetQuotaStatuses(arg1) {
  return window['go']['main']['App']['GetQuotaStatuses'](arg1);
}

export function GetRateLimitStatus(arg1) {
  return window['go']['main']['App']['GetRateLimitStatus'](arg1);
}

export function GetRelayRoutingConfig() {
  return window['go']['main']['App']['GetRelayRoutingConfig']();
}

export function GetRelayServiceConfig() {
  return window['go']['main']['App']['GetRelayServiceConfig']();
}

export function GetReleaseLabel() {
  return window['go']['main']['App']['GetReleaseLabel']();
}

export function GetSidecarProxySettings() {
  return window['go']['main']['App']['GetSidecarProxySettings']();
}

export function GetSidecarStatus() {
  return window['go']['main']['App']['GetSidecarStatus']();
}

export function GetSidecarUsageAttribution(arg1) {
  return window['go']['main']['App']['GetSidecarUsageAttribution'](arg1);
}

export function GetUsageStatistics() {
  return window['go']['main']['App']['GetUsageStatistics']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportCodexBinary(arg1) {
  return window['go']['main']['App']['ImportCodexBinary'](arg1);
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListAuthFiles() {
  return window['go']['main']['App']['ListAuthFiles']();
}

export function ListCachedAccounts() {
  return window['go']['main']['App']['ListCachedAccounts']();
}

export function ListChannelRouteDecisions(arg1) {
  return window['go']['main']['App']['ListChannelRouteDecisions'](arg1);
}

export function ListChannelRouteEvents(arg1) {
  return window['go']['main']['App']['ListChannelRouteEvents'](arg1);
}

export function ListCodexAccountInventory() {
  return window['go']['main']['App']['ListCodexAccountInventory']();
}

export function ListLocalCodexProviderViews() {
  return window['go']['main']['App']['ListLocalCodexProviderViews']();
}

export function ListOAuthModelAliases(arg1) {
  return window['go']['main']['App']['ListOAuthModelAliases'](arg1);
}

export function ListOpenAICompatibleProviders() {
  return window['go']['main']['App']['ListOpenAICompatibleProviders']();
}

export function ListProjectCandidatePoolRules(arg1) {
  return window['go']['main']['App']['ListProjectCandidatePoolRules'](arg1);
}

export function ListRateLimitEvents(arg1) {
  return window['go']['main']['App']['ListRateLimitEvents'](arg1);
}

export function ListRateLimitRules(arg1) {
  return window['go']['main']['App']['ListRateLimitRules'](arg1);
}

export function ListRateLimitStrategies() {
  return window['go']['main']['App']['ListRateLimitStrategies']();
}

export function ListRelaySupportedModels() {
  return window['go']['main']['App']['ListRelaySupportedModels']();
}

export function MarkChannelRouteAccountResult(arg1) {
  return window['go']['main']['App']['MarkChannelRouteAccountResult'](arg1);
}

export function NormalizeAuthFileContent(arg1) {
  return window['go']['main']['App']['NormalizeAuthFileContent'](arg1);
}

export function OpenCodexConfigToml() {
  return window['go']['main']['App']['OpenCodexConfigToml']();
}

export function OpenCodexSkillInFinder(arg1) {
  return window['go']['main']['App']['OpenCodexSkillInFinder'](arg1);
}

export function ParseDeepLink(arg1) {
  return window['go']['main']['App']['ParseDeepLink'](arg1);
}

export function PatchClaudeCodeSettings(arg1) {
  return window['go']['main']['App']['PatchClaudeCodeSettings'](arg1);
}

export function PreflightCodexMcpServer(arg1) {
  return window['go']['main']['App']['PreflightCodexMcpServer'](arg1);
}

export function PrepareGetTokensExtensionCodexConfigApply(arg1) {
  return window['go']['main']['App']['PrepareGetTokensExtensionCodexConfigApply'](arg1);
}

export function PreviewCodexFeatureConfig(arg1) {
  return window['go']['main']['App']['PreviewCodexFeatureConfig'](arg1);
}

export function PreviewDeepLinkImport(arg1) {
  return window['go']['main']['App']['PreviewDeepLinkImport'](arg1);
}

export function PreviewGetTokensExtensionCodexConfigDryRun(arg1) {
  return window['go']['main']['App']['PreviewGetTokensExtensionCodexConfigDryRun'](arg1);
}

export function ProbeClaudeCodeAccountRouting(arg1) {
  return window['go']['main']['App']['ProbeClaudeCodeAccountRouting'](arg1);
}

export function ProbeCodexAccountRouting(arg1) {
  return window['go']['main']['App']['ProbeCodexAccountRouting'](arg1);
}

export function ProbeProxyNode(arg1) {
  return window['go']['main']['App']['ProbeProxyNode'](arg1);
}

export function RebuildClaudeLocalUsage() {
  return window['go']['main']['App']['RebuildClaudeLocalUsage']();
}

export function RebuildClaudeLocalUsageDay(arg1) {
  return window['go']['main']['App']['RebuildClaudeLocalUsageDay'](arg1);
}

export function RebuildCodexLocalUsage() {
  return window['go']['main']['App']['RebuildCodexLocalUsage']();
}

export function RebuildCodexLocalUsageDay(arg1) {
  return window['go']['main']['App']['RebuildCodexLocalUsageDay'](arg1);
}

export function RefreshClaudeCodeSessionManagementSnapshot() {
  return window['go']['main']['App']['RefreshClaudeCodeSessionManagementSnapshot']();
}

export function RefreshClaudeLocalUsage() {
  return window['go']['main']['App']['RefreshClaudeLocalUsage']();
}

export function RefreshCodexBinaryAvailable() {
  return window['go']['main']['App']['RefreshCodexBinaryAvailable']();
}

export function RefreshCodexLocalUsage() {
  return window['go']['main']['App']['RefreshCodexLocalUsage']();
}

export function RefreshCodexQuotasBatch(arg1) {
  return window['go']['main']['App']['RefreshCodexQuotasBatch'](arg1);
}

export function RefreshCodexSessionManagementSnapshot() {
  return window['go']['main']['App']['RefreshCodexSessionManagementSnapshot']();
}

export function RemoveCodexSkill(arg1) {
  return window['go']['main']['App']['RemoveCodexSkill'](arg1);
}

export function RevealCodexBinaryVersion(arg1) {
  return window['go']['main']['App']['RevealCodexBinaryVersion'](arg1);
}

export function RunRouteResilienceAction(arg1) {
  return window['go']['main']['App']['RunRouteResilienceAction'](arg1);
}

export function SaveChannelRoutingConfig(arg1) {
  return window['go']['main']['App']['SaveChannelRoutingConfig'](arg1);
}

export function SaveClaudeCodeMcpServer(arg1) {
  return window['go']['main']['App']['SaveClaudeCodeMcpServer'](arg1);
}

export function SaveClaudeCodeMemoryFile(arg1) {
  return window['go']['main']['App']['SaveClaudeCodeMemoryFile'](arg1);
}

export function SaveClaudeCodeSubagent(arg1) {
  return window['go']['main']['App']['SaveClaudeCodeSubagent'](arg1);
}

export function SaveCodexConfigToml(arg1) {
  return window['go']['main']['App']['SaveCodexConfigToml'](arg1);
}

export function SaveCodexFeatureConfig(arg1) {
  return window['go']['main']['App']['SaveCodexFeatureConfig'](arg1);
}

export function SaveCodexMcpServer(arg1) {
  return window['go']['main']['App']['SaveCodexMcpServer'](arg1);
}

export function SaveCodexSkillEnabled(arg1) {
  return window['go']['main']['App']['SaveCodexSkillEnabled'](arg1);
}

export function SetAccountDisabled(arg1, arg2) {
  return window['go']['main']['App']['SetAccountDisabled'](arg1, arg2);
}

export function SetAuthFileStatus(arg1, arg2) {
  return window['go']['main']['App']['SetAuthFileStatus'](arg1, arg2);
}

export function SetCodexModelCatalogSyncEnabled(arg1) {
  return window['go']['main']['App']['SetCodexModelCatalogSyncEnabled'](arg1);
}

export function SetGetTokensExtensionEnabled(arg1) {
  return window['go']['main']['App']['SetGetTokensExtensionEnabled'](arg1);
}

export function StartCodexOAuth() {
  return window['go']['main']['App']['StartCodexOAuth']();
}

export function StartCodexQuotasBatchRefreshJob(arg1) {
  return window['go']['main']['App']['StartCodexQuotasBatchRefreshJob'](arg1);
}

export function TestCodexAPIKeyBillingCurl(arg1) {
  return window['go']['main']['App']['TestCodexAPIKeyBillingCurl'](arg1);
}

export function TestCodexAPIKeyQuotaCurl(arg1) {
  return window['go']['main']['App']['TestCodexAPIKeyQuotaCurl'](arg1);
}

export function UpdateAccountPriority(arg1) {
  return window['go']['main']['App']['UpdateAccountPriority'](arg1);
}

export function UpdateAppRuntimeSettings(arg1) {
  return window['go']['main']['App']['UpdateAppRuntimeSettings'](arg1);
}

export function UpdateCodexAPIKeyConfig(arg1) {
  return window['go']['main']['App']['UpdateCodexAPIKeyConfig'](arg1);
}

export function UpdateCodexAPIKeyLabel(arg1) {
  return window['go']['main']['App']['UpdateCodexAPIKeyLabel'](arg1);
}

export function UpdateCodexAPIKeyPriority(arg1) {
  return window['go']['main']['App']['UpdateCodexAPIKeyPriority'](arg1);
}

export function UpdateCodexSessionProviders(arg1) {
  return window['go']['main']['App']['UpdateCodexSessionProviders'](arg1);
}

export function UpdateLocalProjectedUsageSettings(arg1) {
  return window['go']['main']['App']['UpdateLocalProjectedUsageSettings'](arg1);
}

export function UpdateOAuthModelAliases(arg1) {
  return window['go']['main']['App']['UpdateOAuthModelAliases'](arg1);
}

export function UpdateOpenAICompatibleProvider(arg1) {
  return window['go']['main']['App']['UpdateOpenAICompatibleProvider'](arg1);
}

export function UpdateProjectCandidatePoolRule(arg1) {
  return window['go']['main']['App']['UpdateProjectCandidatePoolRule'](arg1);
}

export function UpdateRateLimitRule(arg1) {
  return window['go']['main']['App']['UpdateRateLimitRule'](arg1);
}

export function UpdateRelayRoutingConfig(arg1) {
  return window['go']['main']['App']['UpdateRelayRoutingConfig'](arg1);
}

export function UpdateRelayServiceAPIKey(arg1) {
  return window['go']['main']['App']['UpdateRelayServiceAPIKey'](arg1);
}

export function UpdateRelayServiceAPIKeys(arg1) {
  return window['go']['main']['App']['UpdateRelayServiceAPIKeys'](arg1);
}

export function UpdateSidecarProxySettings(arg1) {
  return window['go']['main']['App']['UpdateSidecarProxySettings'](arg1);
}

export function UploadAuthFiles(arg1) {
  return window['go']['main']['App']['UploadAuthFiles'](arg1);
}

export function UseCodexBinary(arg1) {
  return window['go']['main']['App']['UseCodexBinary'](arg1);
}

export function UsesNativeUpdaterUI() {
  return window['go']['main']['App']['UsesNativeUpdaterUI']();
}

export function VerifyOpenAICompatibleProvider(arg1) {
  return window['go']['main']['App']['VerifyOpenAICompatibleProvider'](arg1);
}
