// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function GetSidecarStatus() {
  return window['go']['main']['App']['GetSidecarStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}
