// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {main} from '../models';
import {sidecar} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckUpdate():Promise<updater.ReleaseInfo>;

export function CreateCodexAPIKey(arg1:main.CreateCodexAPIKeyInput):Promise<void>;

export function DeleteAuthFiles(arg1:Array<string>):Promise<void>;

export function DeleteCodexAPIKey(arg1:string):Promise<void>;

export function DownloadAuthFile(arg1:string):Promise<main.DownloadFileResponse>;

export function GetAuthFileModels(arg1:string):Promise<Array<Record<string, any>>>;

export function GetCodexQuota(arg1:string):Promise<main.CodexQuotaResponse>;

export function GetReleaseLabel():Promise<string>;

export function GetSidecarStatus():Promise<sidecar.Status>;

export function GetVersion():Promise<string>;

export function ListAccounts():Promise<Array<main.AccountRecord>>;

export function ListAuthFiles():Promise<main.AuthFilesResponse>;

export function SetAuthFileStatus(arg1:string,arg2:boolean):Promise<void>;

export function UploadAuthFiles(arg1:Array<main.UploadFilePayload>):Promise<void>;
